#+TITLE:     Ectorepo: support
#+AUTHOR:    David Conner
#+EMAIL:     noreply@te.xel.io
#+DESCRIPTION: notes
#+PROPERTY: header-args :mkdirp yes
#+PROPERTY: header-args:sh     :tangle-mode (identity #o555) :mkdirp yes
#+PROPERTY: header-args:python :tangle-mode (identity #o644) :mkdirp yes
#+PROPERTY: header-args:conf   :tangle-mode (identity #o444) :mkdirp yes
#+property: header-args:scheme :tangle-mode (identity #o644) :mkdirp yes

#+begin_src emacs-lisp :eval no :exports none :results none
;; Eval with C-x C-e to disable eval confirmation in this buffer
;; ... or set :eval yes
(setq-local org-confirm-babel-evaluate nil)
#+end_src

* Integration

** Org Notes

*** Running scripts on =$_ECTO= content from =$_REPO=

****** TODO _maybe_ use =.dir-locals.el= for setting =ectoroot= ...

+ This won't work well if this notes repository gets absorbed into
  dcunited001/zettlekasten (even as symlink. or git submodule...)
+ direnv may be confusing as well
+ probably best to avoid the refactor and use the ole =Ctrl-C, Ctrl-V= ...
  (shit) i mean ... yasnippets.

** Automation

It would be nice if some of this were automated -- e.g. identification of sqlite3
databases to facilitate generation of sqlite schema diagrams

* Analysis

*** JSON Schema

* Maintenance
** Repo Tools

*** Manifest

Guix environment in =manifest.scm= must be loaded by =buffer-env.el= for tangling to work.

#+begin_src scheme :tangle manifest.scm :eval no
(use-modules (guix packages)
             (gnu packages android)
             (gnu packages python))

(let ((git-repo-with-path
       (manifest-entry
         (name "git-repo")
         (item git-repo)
         (version "2.4.1") ;most recent version
         (search-paths (list (search-path-specification
                              (variable "PYTHONPATH")
                              (files '("share/git-repo")))
                             (search-path-specification
                              (variable "GUIX_PYTHONPATH")
                              (files '("share/git-repo"))))))))

 (concatenate-manifests (list
                         (manifest
                          (list git-repo-with-path))
                          (packages->manifest
                           (list python)))))
#+end_src

**** Package Transformations

See =options->transformations= for info about [[https://guix.gnu.org/manual/en/html_node/Defining-Package-Variants.html][package variants]].

#+begin_example scheme
(package
  (name "hello-simd")
  ;; ...

  ;; This package may benefit from SIMD extensions so
  ;; mark it as "tunable".
  (properties '((tunable? . #t))))
#+end_example

+ =(tunable ...)=
+ =(with-source "/file/or/url.tar.gz")=
+ or =(with-input...)=
+ or =(with-graft...)=

The last of these enables hacking on source checkouts. To use it with
=git-repo=, create a new package that inherits from the intended package and
replace the =(source...)= declaration with a reference to the project's path in
the sync'd repo superproject. There may be a be a better way to do this: =guix
build --help-transform=.

*** Environment

When running the scripts, prefix them with =guix shell -m manifest.scm -- python
$script=. This is the most consistent way to do this in emacs.

The =buffer-env= package will load the correct environment when commands via
=[C-u] M-!=, but trying to get this to work with =org-babel= requires too much
init.el-specific configuration or unsatisfactory boilerplate. This is mainly an
org-babel problem.

For example, the org-babel header =:python (expand-file-name "bin/python3"
(getenv "GUIX_ENVIRONMENT"))= will give the =GUIX_ENVIRONMENT= used to start
emacs. Other ways to addess include =.env= scripts, which aren't necessarily
portable.

*** Repo Checkout Maintainence
**** Prune git indices

#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto
# could be dangerous if processes are writing to objects in .git
repo forall -c 'git gc --aggressive --prune=now'
#+end_src

***** Diff

For repo's that get sync'd frequently, this could save between 50-75% storage,
depending on code churn. It could be much higher with branches.

#+begin_quote
Run three of these with =repo forall= and watch in amazement as your tabs crash...

Three was maxing out I/O, CPU and RAM for me. I had to kill chromium to ward off
the OOM killer, since I don't swap.
#+end_quote

Running on =clab, vyos, tensorflow, frc, x.files=

#+begin_quote
Before: =/dev/mapper/vgcrypt-data   443G  335G   86G  80% /data=
After: =/dev/mapper/vgcrypt-data   443G  327G   94G  78% /data=
#+end_quote

It's not a particularly fun way to save space though.

****** Between =.repo/project-objects= & Checkouts

Differences between =.repo/project-objects= & checkouts

#+name: vyosDuDiff
#+begin_src shell :results output table :var checkoutDu=vyosDu repoDu=vyosRepoDu :dir /data/ecto
paste <(echo "${checkoutDu[@]}") <(echo "${repoDu[@]}") 
#+end_src

#+RESULTS: vyosDuDiff
| 299628 | vyos/vyos-documentation              | 236812 | .repo/project-objects/frrouting/frr.git                      |
| 223000 | yang/yangsuite                       | 141616 | .repo/project-objects/vyos/vyos-documentation.git            |
| 120564 | vyos/vyos-1x                         | 137752 | .repo/project-objects/srl-labs/containerlab.git              |
|  51992 | frr/tests                            |  79852 | .repo/project-objects/CiscoDevNet/yangsuite.git              |
|  48396 | vyos/vyos-build                      |  70876 | .repo/project-objects/vyos/infinitytier.git                  |
|  21560 | vyos/vyatta-bash                     |  61844 | .repo/project-objects/CESNET/libyang.git                     |
|  18644 | vyos/zbackup_vyos-workflow-test-temp |  42848 | .repo/project-objects/vyos/vyos-1x.git                       |
|  15316 | vyos/efi-boot-shim                   |  33856 | .repo/project-objects/vyos/gh-action-test-vyos-1x.git        |
|  13952 | yang/pyang                           |  25164 | .repo/project-objects/vyos/vyos-cloud-init.git               |
|  11360 | yang/libyang                         |  25128 | .repo/project-objects/vyos/vyos-strongswan.git               |
|   9444 | srl-labs/containerlab                |  18424 | .repo/project-objects/vyos/vyos-live-build.git               |
|   8588 | vyos/vyos.vyos                       |  17432 | .repo/project-objects/vyos/efi-boot-shim.git                 |
|   7892 | vyos/vyos-cloud-init                 |  14064 | .repo/project-objects/vyos/vyos-build.git                    |
|   6792 | frr/bgpd                             |  10380 | .repo/project-objects/mbj4668/pyang.git                      |
|   6228 | frr/doc                              |   8664 | .repo/project-objects/vyos/shim-signed.git                   |
|   4404 | frr/lib                              |   7196 | .repo/project-objects/vyos/vyatta-bash.git                   |
|   4140 | vyos/shim-signed                     |   6372 | .repo/project-objects/vyos/vyos.vyos.git                     |
|   3900 | frr/zebra                            |   5164 | .repo/project-objects/vyos/vyatta-cfg-system.git             |
|   2796 | vyos/vyos-live-build                 |   5040 | .repo/project-objects/vyos/vyatta-cfg-quagga.git             |
|   2492 | frr/pimd                             |   4592 | .repo/project-objects/vyos/vyatta-cfg.git                    |
|   2256 | frr/ospfd                            |   3816 | .repo/project-objects/vyos/vyos-walinuxagent.git             |
|   1904 | frr/isisd                            |   3112 | .repo/project-objects/vyos/vyconf.git                        |
|   1304 | vyos/vyos-automation                 |   3044 | .repo/project-objects/vyos/vyos-workflow-test-temp.git       |
|   1264 | frr/tools                            |   2900 | .repo/project-objects/vyos/live-boot.git                     |
|   1240 | vyos/rest.vyos                       |   2696 | .repo/project-objects/vyos/vyos-vpp-patches.git              |
|   1224 | vyos/vyatta-cfg                      |   2620 | .repo/project-objects/vyos/vyos-nightly-build.git            |
|   1188 | frr/ospf6d                           |   2476 | .repo/project-objects/vyos/vyos1x-config.git                 |
|   1044 | frr/pceplib                          |   2444 | .repo/project-objects/vyos/conntrack-tools.git               |
|    908 | frr/yang                             |   2108 | .repo/project-objects/vyos/community.vyos.net.git            |
|    852 | vyos/live-boot                       |   2036 | .repo/project-objects/huihuimoe/vyos-arm64-build.git         |
|    720 | frr/ldpd                             |   1956 | .repo/project-objects/vyos/libpam-radius-auth.git            |
|    688 | vyos/vyatta-cfg-system               |   1948 | .repo/project-objects/vyos/vyatta-op.git                     |
|    656 | vyos/vyconf                          |   1804 | .repo/project-objects/vyos/vyos-workflow-testing.git         |
|    616 | vyos/community.vyos.net              |   1616 | .repo/project-objects/vyos/vyos-cla-signatures.git           |
|    580 | frr/pathd                            |   1564 | .repo/project-objects/vyos/ipaddrcheck.git                   |
|    536 | vyos/vyatta-biosdevname              |   1536 | .repo/project-objects/vyos/vyos-utils.git                    |
|    532 | frr/eigrpd                           |   1452 | .repo/project-objects/vyos/vyos-automation.git               |
|    512 | frr/bfdd                             |   1396 | .repo/project-objects/vyos/vyos-vpp.git                      |
|    492 | vyos/libpam-tacplus                  |   1364 | .repo/project-objects/vyos/libvyosconfig.git                 |
|    444 | vyos/vyos-vpp-patches                |   1360 | .repo/project-objects/vyos/vyos-http-api-tools.git           |
|    428 | vyos/libpam-radius-auth              |   1176 | .repo/project-objects/vyos/vyos-utils-misc.git               |
|    376 | frr/ripd                             |   1164 | .repo/project-objects/vyos/libtacplus-map.git                |
|    356 | frr/staticd                          |   1144 | .repo/project-objects/vyos/vyos-infrastructure.git           |
|    336 | vyos/vyos1x-config                   |   1128 | .repo/project-objects/budimanjojo/vyos-config.git            |
|    332 | frr/nhrpd                            |   1124 | .repo/project-objects/vyos/vyatta-cfg-firewall.git           |
|    332 | frr/mgmtd                            |   1104 | .repo/project-objects/vyos/vyatta-biosdevname.git            |
|    316 | frr/babeld                           |   1044 | .repo/project-objects/vyos/libnss-mapuser.git                |
|    300 | misc/budimanjojo                     |   1028 | .repo/project-objects/vyos/hvinfo.git                        |
|    284 | vyos/vyos-nightly-build              |    996 | .repo/project-objects/vyos/vyatta-cfg-vpn.git                |
|    280 | vyos/ipaddrcheck                     |    956 | .repo/project-objects/vyos/libpam-tacplus.git                |
|    276 | misc/huihuimoe                       |    940 | .repo/project-objects/vyos/mergify.git                       |
|    264 | frr/ripngd                           |    928 | .repo/project-objects/vyos/vyatta-cfg-qos.git                |
|    252 | frr/debian                           |    888 | .repo/project-objects/vyos/shim-review.git                   |
|    236 | frr/vtysh                            |    880 | .repo/project-objects/vyos/vyos-github-actions.git           |
|    220 | frr/vrrpd                            |    872 | .repo/project-objects/vyos/libnss-tacplus.git                |
|    216 | frr/include                          |    792 | .repo/project-objects/vyos/vyatta-wanloadbalance.git         |
|    208 | frr/pbrd                             |    764 | .repo/project-objects/vyos/initramfs-tools.git               |
|    200 | misc/mu-ruU1                         |    608 | .repo/project-objects/mbj4668/yang-mode.git                  |
|    188 | vyos/libnss-mapuser                  |    576 | .repo/project-objects/vyos/tacplusd.git                      |
|    188 | frr/snapcraft                        |    552 | .repo/project-objects/vyos/uncron.git                        |
|    180 | vyos/libtacplus-map                  |    536 | .repo/project-objects/vyos/vyatta-op-vpn.git                 |
|    164 | vyos/hvinfo                          |    476 | .repo/project-objects/vyos/MAC-Telnet.git                    |
|    164 | frr/docker                           |    460 | .repo/project-objects/vyos/pam_tacplus.git                   |
|    148 | frr/python                           |    440 | .repo/project-objects/vyos/libmnl.git                        |
|    136 | frr/sharpd                           |    436 | .repo/project-objects/srl-labs/network-multitool.git         |
|    128 | vyos/phorge-elasticsearch-modern     |    408 | .repo/project-objects/vyos/vyatta-nat.git                    |
|    124 | vyos/vyos-utils-misc                 |    400 | .repo/project-objects/vyos/vyos-user-utils.git               |
|    124 | frr/m4                               |    384 | .repo/project-objects/vyos/rest.vyos.git                     |
|    112 | frr/ospfclient                       |    376 | .repo/project-objects/vyos/vyatta-conntrack.git              |
|    100 | vyos/vyos-github-actions             |    336 | .repo/project-objects/vyos/udp-broadcast-relay.git           |
|    100 | vyos/mirror-canary                   |    328 | .repo/project-objects/vyos/vyos-opennhrp.git                 |
|     92 | frr/redhat                           |    328 | .repo/project-objects/vyos/amplify-build-status.git          |
|     92 | frr/configure.ac                     |    320 | .repo/project-objects/yunzheng/vyos-arm64-iso.git            |
|     88 | vyos/vyos-http-api-tools             |    300 | .repo/project-objects/vyos/ticket-app.git                    |
|     84 | vyos/vyos-infrastructure             |    284 | .repo/project-objects/vyos/vyatta-op-firewall.git            |
|     80 | frr/watchfrr                         |    276 | .repo/project-objects/vyos/vyos-salt-minion.git              |
|     72 | vyos/vyos-cla-signatures             |    216 | .repo/project-objects/vyos/vyos-world.git                    |
|     60 | srl-labs/network-multitool           |    216 | .repo/project-objects/vyos/public-images.git                 |
|     56 | misc/yunzheng                        |    212 | .repo/project-objects/vyos/vyatta-op-qos.git                 |
|     52 | frr/gdb                              |    212 | .repo/project-objects/vyos/vyatta-cluster.git                |
|     44 | vyos/mergify                         |    208 | .repo/project-objects/vyos/vyos.git                          |
|     44 | frr/qpb                              |    204 | .repo/project-objects/vyos/vyos-community-flavors.git        |
|     44 | frr/pkgsrc                           |    204 | .repo/project-objects/vyos/vyatta-config-mgmt.git            |
|     44 | frr/fpm                              |    192 | .repo/project-objects/mu-ruU1/vyos-build-container-image.git |
|     28 | frr/grpc                             |    184 | .repo/project-objects/vyos/vyos-xe-guest-utilities.git       |
|     24 | yang/yang-mode                       |    152 | .repo/project-objects/vyos/vyos-nhrp.git                     |
|     24 | frr/alpine                           |    148 | .repo/project-objects/vyos/vyatta-zone.git                   |
|     20 | frr/mlag                             |    144 | .repo/project-objects/vyos/phorge-elasticsearch-modern.git   |
|     12 | frr/Makefile.am                      |    144 | .repo/project-objects/vyos/openvpn-duo-plugin.git            |
|      8 | vyos/gh-action-test                  |    140 | .repo/project-objects/vyos/vyos-sdk.git                      |
|      4 | frr/version.h                        |    120 | .repo/project-objects/vyos/vyos-community-process.git        |
|      4 | frr/stamp-h.in                       |    116 | .repo/project-objects/vyos/mirror-canary.git                 |
|      4 | frr/README.md                        |    112 | .repo/project-objects/vyos/mdns-repeater.git                 |
|      4 | frr/COPYING                          |     80 | .repo/project-objects/vyos/gh-action-test.git                |
|      4 | frr/config.version.in                |        |                                                              |
|      4 | frr/buildtest.sh                     |        |                                                              |
|      4 | frr/bootstrap.sh                     |        |                                                              |
|        |                                      |        |                                                              |

And after =git-gc --aggressive --prune=now=:

#+name: vyosDuDiffAfter
#+call: vyosDuDiff(checkoutDu=vyosDuAfter, repoDu=vyosRepoDuAfter)

#+RESULTS: vyosDuDiffAfter
| 299628 | vyos/vyos-documentation              | 89072 | .repo/project-objects/vyos/vyos-documentation.git            |
| 223000 | yang/yangsuite                       | 82924 | .repo/project-objects/frrouting/frr.git                      |
| 120564 | vyos/vyos-1x                         | 81788 | .repo/project-objects/srl-labs/containerlab.git              |
|  51992 | frr/tests                            | 79432 | .repo/project-objects/CiscoDevNet/yangsuite.git              |
|  48396 | vyos/vyos-build                      | 70876 | .repo/project-objects/vyos/infinitytier.git                  |
|  21560 | vyos/vyatta-bash                     | 33856 | .repo/project-objects/vyos/gh-action-test-vyos-1x.git        |
|  18644 | vyos/zbackup_vyos-workflow-test-temp | 25128 | .repo/project-objects/vyos/vyos-strongswan.git               |
|  15316 | vyos/efi-boot-shim                   | 23520 | .repo/project-objects/vyos/vyos-1x.git                       |
|  13952 | yang/pyang                           | 23404 | .repo/project-objects/CESNET/libyang.git                     |
|  11360 | yang/libyang                         | 17912 | .repo/project-objects/vyos/vyos-live-build.git               |
|   9444 | srl-labs/containerlab                | 12064 | .repo/project-objects/vyos/efi-boot-shim.git                 |
|   8588 | vyos/vyos.vyos                       | 10376 | .repo/project-objects/vyos/vyos-build.git                    |
|   7892 | vyos/vyos-cloud-init                 |  9160 | .repo/project-objects/vyos/vyos-cloud-init.git               |
|   6792 | frr/bgpd                             |  8292 | .repo/project-objects/mbj4668/pyang.git                      |
|   6228 | frr/doc                              |  7924 | .repo/project-objects/vyos/shim-signed.git                   |
|   4404 | frr/lib                              |  5636 | .repo/project-objects/vyos/vyatta-bash.git                   |
|   4140 | vyos/shim-signed                     |  5040 | .repo/project-objects/vyos/vyatta-cfg-quagga.git             |
|   3900 | frr/zebra                            |  4124 | .repo/project-objects/vyos/vyatta-cfg-system.git             |
|   2796 | vyos/vyos-live-build                 |  3816 | .repo/project-objects/vyos/vyos-walinuxagent.git             |
|   2492 | frr/pimd                             |  3044 | .repo/project-objects/vyos/vyos-workflow-test-temp.git       |
|   2256 | frr/ospfd                            |  2536 | .repo/project-objects/vyos/vyatta-cfg.git                    |
|   1904 | frr/isisd                            |  2444 | .repo/project-objects/vyos/conntrack-tools.git               |
|   1304 | vyos/vyos-automation                 |  2340 | .repo/project-objects/vyos/vyos.vyos.git                     |
|   1264 | frr/tools                            |  2036 | .repo/project-objects/vyos/live-boot.git                     |
|   1240 | vyos/rest.vyos                       |  1948 | .repo/project-objects/vyos/vyatta-op.git                     |
|   1224 | vyos/vyatta-cfg                      |  1804 | .repo/project-objects/vyos/vyos-workflow-testing.git         |
|   1188 | frr/ospf6d                           |  1536 | .repo/project-objects/vyos/vyos-utils.git                    |
|   1044 | frr/pceplib                          |  1396 | .repo/project-objects/vyos/vyos-vpp.git                      |
|    908 | frr/yang                             |  1364 | .repo/project-objects/vyos/libvyosconfig.git                 |
|    852 | vyos/live-boot                       |  1124 | .repo/project-objects/vyos/vyatta-cfg-firewall.git           |
|    720 | frr/ldpd                             |   996 | .repo/project-objects/vyos/vyatta-cfg-vpn.git                |
|    688 | vyos/vyatta-cfg-system               |   928 | .repo/project-objects/vyos/vyatta-cfg-qos.git                |
|    656 | vyos/vyconf                          |   888 | .repo/project-objects/vyos/shim-review.git                   |
|    616 | vyos/community.vyos.net              |   872 | .repo/project-objects/vyos/libnss-tacplus.git                |
|    580 | frr/pathd                            |   792 | .repo/project-objects/vyos/vyatta-wanloadbalance.git         |
|    536 | vyos/vyatta-biosdevname              |   764 | .repo/project-objects/vyos/initramfs-tools.git               |
|    532 | frr/eigrpd                           |   756 | .repo/project-objects/vyos/vyos-nightly-build.git            |
|    512 | frr/bfdd                             |   628 | .repo/project-objects/vyos/community.vyos.net.git            |
|    492 | vyos/libpam-tacplus                  |   592 | .repo/project-objects/vyos/vyconf.git                        |
|    444 | vyos/vyos-vpp-patches                |   576 | .repo/project-objects/vyos/tacplusd.git                      |
|    428 | vyos/libpam-radius-auth              |   552 | .repo/project-objects/vyos/uncron.git                        |
|    376 | frr/ripd                             |   536 | .repo/project-objects/vyos/vyatta-op-vpn.git                 |
|    356 | frr/staticd                          |   516 | .repo/project-objects/vyos/vyos-automation.git               |
|    336 | vyos/vyos1x-config                   |   476 | .repo/project-objects/vyos/MAC-Telnet.git                    |
|    332 | frr/nhrpd                            |   464 | .repo/project-objects/vyos/libpam-radius-auth.git            |
|    332 | frr/mgmtd                            |   460 | .repo/project-objects/vyos/pam_tacplus.git                   |
|    316 | frr/babeld                           |   440 | .repo/project-objects/vyos/libmnl.git                        |
|    300 | misc/budimanjojo                     |   408 | .repo/project-objects/vyos/vyatta-nat.git                    |
|    284 | vyos/vyos-nightly-build              |   400 | .repo/project-objects/vyos/vyos-user-utils.git               |
|    280 | vyos/ipaddrcheck                     |   376 | .repo/project-objects/vyos/vyatta-conntrack.git              |
|    276 | misc/huihuimoe                       |   360 | .repo/project-objects/huihuimoe/vyos-arm64-build.git         |
|    264 | frr/ripngd                           |   336 | .repo/project-objects/vyos/udp-broadcast-relay.git           |
|    252 | frr/debian                           |   328 | .repo/project-objects/vyos/vyos-opennhrp.git                 |
|    236 | frr/vtysh                            |   328 | .repo/project-objects/vyos/amplify-build-status.git          |
|    220 | frr/vrrpd                            |   320 | .repo/project-objects/vyos/vyos1x-config.git                 |
|    216 | frr/include                          |   320 | .repo/project-objects/vyos/vyatta-biosdevname.git            |
|    208 | frr/pbrd                             |   316 | .repo/project-objects/vyos/rest.vyos.git                     |
|    200 | misc/mu-ruU1                         |   308 | .repo/project-objects/vyos/vyos-vpp-patches.git              |
|    188 | vyos/libnss-mapuser                  |   300 | .repo/project-objects/vyos/ticket-app.git                    |
|    188 | frr/snapcraft                        |   284 | .repo/project-objects/vyos/vyatta-op-firewall.git            |
|    180 | vyos/libtacplus-map                  |   280 | .repo/project-objects/vyos/ipaddrcheck.git                   |
|    164 | vyos/hvinfo                          |   276 | .repo/project-objects/vyos/vyos-salt-minion.git              |
|    164 | frr/docker                           |   256 | .repo/project-objects/budimanjojo/vyos-config.git            |
|    148 | frr/python                           |   216 | .repo/project-objects/vyos/vyos-world.git                    |
|    136 | frr/sharpd                           |   216 | .repo/project-objects/vyos/public-images.git                 |
|    128 | vyos/phorge-elasticsearch-modern     |   212 | .repo/project-objects/vyos/vyatta-op-qos.git                 |
|    124 | vyos/vyos-utils-misc                 |   212 | .repo/project-objects/vyos/vyatta-cluster.git                |
|    124 | frr/m4                               |   208 | .repo/project-objects/vyos/vyos.git                          |
|    112 | frr/ospfclient                       |   204 | .repo/project-objects/vyos/vyos-community-flavors.git        |
|    100 | vyos/vyos-github-actions             |   204 | .repo/project-objects/vyos/vyatta-config-mgmt.git            |
|    100 | vyos/mirror-canary                   |   204 | .repo/project-objects/vyos/libpam-tacplus.git                |
|     92 | frr/redhat                           |   200 | .repo/project-objects/mu-ruU1/vyos-build-container-image.git |
|     92 | frr/configure.ac                     |   188 | .repo/project-objects/vyos/libnss-mapuser.git                |
|     88 | vyos/vyos-http-api-tools             |   188 | .repo/project-objects/vyos/hvinfo.git                        |
|     84 | vyos/vyos-infrastructure             |   184 | .repo/project-objects/vyos/vyos-xe-guest-utilities.git       |
|     80 | frr/watchfrr                         |   176 | .repo/project-objects/vyos/vyos-http-api-tools.git           |
|     72 | vyos/vyos-cla-signatures             |   172 | .repo/project-objects/vyos/vyos-cla-signatures.git           |
|     60 | srl-labs/network-multitool           |   152 | .repo/project-objects/vyos/vyos-nhrp.git                     |
|     56 | misc/yunzheng                        |   148 | .repo/project-objects/vyos/vyatta-zone.git                   |
|     52 | frr/gdb                              |   144 | .repo/project-objects/vyos/phorge-elasticsearch-modern.git   |
|     44 | vyos/mergify                         |   144 | .repo/project-objects/vyos/openvpn-duo-plugin.git            |
|     44 | frr/qpb                              |   140 | .repo/project-objects/vyos/vyos-sdk.git                      |
|     44 | frr/pkgsrc                           |   140 | .repo/project-objects/vyos/libtacplus-map.git                |
|     44 | frr/fpm                              |   128 | .repo/project-objects/vyos/mirror-canary.git                 |
|     28 | frr/grpc                             |   124 | .repo/project-objects/vyos/vyos-infrastructure.git           |
|     24 | yang/yang-mode                       |   124 | .repo/project-objects/vyos/vyos-github-actions.git           |
|     24 | frr/alpine                           |   124 | .repo/project-objects/vyos/mergify.git                       |
|     20 | frr/mlag                             |   120 | .repo/project-objects/vyos/vyos-utils-misc.git               |
|     12 | frr/Makefile.am                      |   120 | .repo/project-objects/vyos/vyos-community-process.git        |
|      8 | vyos/gh-action-test                  |   120 | .repo/project-objects/srl-labs/network-multitool.git         |
|      4 | frr/version.h                        |   112 | .repo/project-objects/vyos/mdns-repeater.git                 |
|      4 | frr/stamp-h.in                       |    88 | .repo/project-objects/mbj4668/yang-mode.git                  |
|      4 | frr/README.md                        |    80 | .repo/project-objects/yunzheng/vyos-arm64-iso.git            |
|      4 | frr/COPYING                          |    76 | .repo/project-objects/vyos/gh-action-test.git                |
|      4 | frr/config.version.in                |       |                                                              |
|      4 | frr/buildtest.sh                     |       |                                                              |
|      4 | frr/bootstrap.sh                     |       |                                                              |
|        |                                      |       |                                                              |

****** Comparing each type (checkout, objects), before/after

Differences in checkouts, before/after (almost none)

#+name: vyosDuDiffProjects
#+begin_src shell :results output code :wrap example diff :var checkoutDu=vyosDu repoDu=vyosDuAfter :dir /data/ecto
diff <(echo "${checkoutDu[@]}") <(echo "${repoDu[@]}")
# exactly none
#+end_src

#+RESULTS: vyosDuDiffProjects
#+begin_example diff
#+end_example

Differences in =.repo/project-objects=, before/after (significant)

#+name: vyosDuDiffObjects
#+begin_src shell :results output code :wrap example diff :var checkoutDu=vyosRepoDu repoDu=vyosRepoDuAfter :dir /data/ecto
diff <(echo "${checkoutDu[@]}" | sort -k2) <(echo "${repoDu[@]}" | sort -k2)
# exactly none
#+end_src

#+call: vyosDuDiff(checkoutDu=vyosRepoDu, repoDu=vyosRepoDuAfter)

#+RESULTS: vyosDuDiffObjects
#+begin_example diff
2,11c2,11
< 1128	.repo/project-objects/budimanjojo/vyos-config.git
< 61844	.repo/project-objects/CESNET/libyang.git
< 79852	.repo/project-objects/CiscoDevNet/yangsuite.git
< 236812	.repo/project-objects/frrouting/frr.git
< 2036	.repo/project-objects/huihuimoe/vyos-arm64-build.git
< 10380	.repo/project-objects/mbj4668/pyang.git
< 608	.repo/project-objects/mbj4668/yang-mode.git
< 192	.repo/project-objects/mu-ruU1/vyos-build-container-image.git
< 137752	.repo/project-objects/srl-labs/containerlab.git
< 436	.repo/project-objects/srl-labs/network-multitool.git
---
> 256	.repo/project-objects/budimanjojo/vyos-config.git
> 23404	.repo/project-objects/CESNET/libyang.git
> 79432	.repo/project-objects/CiscoDevNet/yangsuite.git
> 82924	.repo/project-objects/frrouting/frr.git
> 360	.repo/project-objects/huihuimoe/vyos-arm64-build.git
> 8292	.repo/project-objects/mbj4668/pyang.git
> 88	.repo/project-objects/mbj4668/yang-mode.git
> 200	.repo/project-objects/mu-ruU1/vyos-build-container-image.git
> 81788	.repo/project-objects/srl-labs/containerlab.git
> 120	.repo/project-objects/srl-labs/network-multitool.git
13c13
< 2108	.repo/project-objects/vyos/community.vyos.net.git
---
> 628	.repo/project-objects/vyos/community.vyos.net.git
15,16c15,16
< 17432	.repo/project-objects/vyos/efi-boot-shim.git
< 80	.repo/project-objects/vyos/gh-action-test.git
---
> 12064	.repo/project-objects/vyos/efi-boot-shim.git
> 76	.repo/project-objects/vyos/gh-action-test.git
18c18
< 1028	.repo/project-objects/vyos/hvinfo.git
---
> 188	.repo/project-objects/vyos/hvinfo.git
21c21
< 1564	.repo/project-objects/vyos/ipaddrcheck.git
---
> 280	.repo/project-objects/vyos/ipaddrcheck.git
23c23
< 1044	.repo/project-objects/vyos/libnss-mapuser.git
---
> 188	.repo/project-objects/vyos/libnss-mapuser.git
25,27c25,27
< 1956	.repo/project-objects/vyos/libpam-radius-auth.git
< 956	.repo/project-objects/vyos/libpam-tacplus.git
< 1164	.repo/project-objects/vyos/libtacplus-map.git
---
> 464	.repo/project-objects/vyos/libpam-radius-auth.git
> 204	.repo/project-objects/vyos/libpam-tacplus.git
> 140	.repo/project-objects/vyos/libtacplus-map.git
29c29
< 2900	.repo/project-objects/vyos/live-boot.git
---
> 2036	.repo/project-objects/vyos/live-boot.git
32,33c32,33
< 940	.repo/project-objects/vyos/mergify.git
< 116	.repo/project-objects/vyos/mirror-canary.git
---
> 124	.repo/project-objects/vyos/mergify.git
> 128	.repo/project-objects/vyos/mirror-canary.git
38c38
< 384	.repo/project-objects/vyos/rest.vyos.git
---
> 316	.repo/project-objects/vyos/rest.vyos.git
40c40
< 8664	.repo/project-objects/vyos/shim-signed.git
---
> 7924	.repo/project-objects/vyos/shim-signed.git
45,46c45,46
< 7196	.repo/project-objects/vyos/vyatta-bash.git
< 1104	.repo/project-objects/vyos/vyatta-biosdevname.git
---
> 5636	.repo/project-objects/vyos/vyatta-bash.git
> 320	.repo/project-objects/vyos/vyatta-biosdevname.git
48c48
< 4592	.repo/project-objects/vyos/vyatta-cfg.git
---
> 2536	.repo/project-objects/vyos/vyatta-cfg.git
51c51
< 5164	.repo/project-objects/vyos/vyatta-cfg-system.git
---
> 4124	.repo/project-objects/vyos/vyatta-cfg-system.git
63,69c63,69
< 3112	.repo/project-objects/vyos/vyconf.git
< 2476	.repo/project-objects/vyos/vyos1x-config.git
< 42848	.repo/project-objects/vyos/vyos-1x.git
< 1452	.repo/project-objects/vyos/vyos-automation.git
< 14064	.repo/project-objects/vyos/vyos-build.git
< 1616	.repo/project-objects/vyos/vyos-cla-signatures.git
< 25164	.repo/project-objects/vyos/vyos-cloud-init.git
---
> 592	.repo/project-objects/vyos/vyconf.git
> 320	.repo/project-objects/vyos/vyos1x-config.git
> 23520	.repo/project-objects/vyos/vyos-1x.git
> 516	.repo/project-objects/vyos/vyos-automation.git
> 10376	.repo/project-objects/vyos/vyos-build.git
> 172	.repo/project-objects/vyos/vyos-cla-signatures.git
> 9160	.repo/project-objects/vyos/vyos-cloud-init.git
72c72
< 141616	.repo/project-objects/vyos/vyos-documentation.git
---
> 89072	.repo/project-objects/vyos/vyos-documentation.git
74,77c74,77
< 880	.repo/project-objects/vyos/vyos-github-actions.git
< 1360	.repo/project-objects/vyos/vyos-http-api-tools.git
< 1144	.repo/project-objects/vyos/vyos-infrastructure.git
< 18424	.repo/project-objects/vyos/vyos-live-build.git
---
> 124	.repo/project-objects/vyos/vyos-github-actions.git
> 176	.repo/project-objects/vyos/vyos-http-api-tools.git
> 124	.repo/project-objects/vyos/vyos-infrastructure.git
> 17912	.repo/project-objects/vyos/vyos-live-build.git
79c79
< 2620	.repo/project-objects/vyos/vyos-nightly-build.git
---
> 756	.repo/project-objects/vyos/vyos-nightly-build.git
86c86
< 1176	.repo/project-objects/vyos/vyos-utils-misc.git
---
> 120	.repo/project-objects/vyos/vyos-utils-misc.git
88,89c88,89
< 2696	.repo/project-objects/vyos/vyos-vpp-patches.git
< 6372	.repo/project-objects/vyos/vyos.vyos.git
---
> 308	.repo/project-objects/vyos/vyos-vpp-patches.git
> 2340	.repo/project-objects/vyos/vyos.vyos.git
95c95
< 320	.repo/project-objects/yunzheng/vyos-arm64-iso.git
---
> 80	.repo/project-objects/yunzheng/vyos-arm64-iso.git
#+end_example

***** Before

#+name: vyosDu
#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto :cache yes
cd $repoproject
du -s **/* | sort -nr
#+end_src

#+RESULTS[6e8d8d9a69cc76927fcd3fc8639f67f20ef74785]: vyosDu
#+begin_example
299628	vyos/vyos-documentation
223000	yang/yangsuite
120564	vyos/vyos-1x
51992	frr/tests
48396	vyos/vyos-build
21560	vyos/vyatta-bash
18644	vyos/zbackup_vyos-workflow-test-temp
15316	vyos/efi-boot-shim
13952	yang/pyang
11360	yang/libyang
9444	srl-labs/containerlab
8588	vyos/vyos.vyos
7892	vyos/vyos-cloud-init
6792	frr/bgpd
6228	frr/doc
4404	frr/lib
4140	vyos/shim-signed
3900	frr/zebra
2796	vyos/vyos-live-build
2492	frr/pimd
2256	frr/ospfd
1904	frr/isisd
1304	vyos/vyos-automation
1264	frr/tools
1240	vyos/rest.vyos
1224	vyos/vyatta-cfg
1188	frr/ospf6d
1044	frr/pceplib
908	frr/yang
852	vyos/live-boot
720	frr/ldpd
688	vyos/vyatta-cfg-system
656	vyos/vyconf
616	vyos/community.vyos.net
580	frr/pathd
536	vyos/vyatta-biosdevname
532	frr/eigrpd
512	frr/bfdd
492	vyos/libpam-tacplus
444	vyos/vyos-vpp-patches
428	vyos/libpam-radius-auth
376	frr/ripd
356	frr/staticd
336	vyos/vyos1x-config
332	frr/nhrpd
332	frr/mgmtd
316	frr/babeld
300	misc/budimanjojo
284	vyos/vyos-nightly-build
280	vyos/ipaddrcheck
276	misc/huihuimoe
264	frr/ripngd
252	frr/debian
236	frr/vtysh
220	frr/vrrpd
216	frr/include
208	frr/pbrd
200	misc/mu-ruU1
188	vyos/libnss-mapuser
188	frr/snapcraft
180	vyos/libtacplus-map
164	vyos/hvinfo
164	frr/docker
148	frr/python
136	frr/sharpd
128	vyos/phorge-elasticsearch-modern
124	vyos/vyos-utils-misc
124	frr/m4
112	frr/ospfclient
100	vyos/vyos-github-actions
100	vyos/mirror-canary
92	frr/redhat
92	frr/configure.ac
88	vyos/vyos-http-api-tools
84	vyos/vyos-infrastructure
80	frr/watchfrr
72	vyos/vyos-cla-signatures
60	srl-labs/network-multitool
56	misc/yunzheng
52	frr/gdb
44	vyos/mergify
44	frr/qpb
44	frr/pkgsrc
44	frr/fpm
28	frr/grpc
24	yang/yang-mode
24	frr/alpine
20	frr/mlag
12	frr/Makefile.am
8	vyos/gh-action-test
4	frr/version.h
4	frr/stamp-h.in
4	frr/README.md
4	frr/COPYING
4	frr/config.version.in
4	frr/buildtest.sh
4	frr/bootstrap.sh
#+end_example

#+name: vyosRepoDu
#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto :cache yes
cd $repoproject
du -s .repo/project-objects/**/* | sort -nr
#+end_src

#+RESULTS[a64a8f78c42659781377f03ca1ac1f3efcbeb43a]: vyosRepoDu
#+begin_example
236812	.repo/project-objects/frrouting/frr.git
141616	.repo/project-objects/vyos/vyos-documentation.git
137752	.repo/project-objects/srl-labs/containerlab.git
79852	.repo/project-objects/CiscoDevNet/yangsuite.git
70876	.repo/project-objects/vyos/infinitytier.git
61844	.repo/project-objects/CESNET/libyang.git
42848	.repo/project-objects/vyos/vyos-1x.git
33856	.repo/project-objects/vyos/gh-action-test-vyos-1x.git
25164	.repo/project-objects/vyos/vyos-cloud-init.git
25128	.repo/project-objects/vyos/vyos-strongswan.git
18424	.repo/project-objects/vyos/vyos-live-build.git
17432	.repo/project-objects/vyos/efi-boot-shim.git
14064	.repo/project-objects/vyos/vyos-build.git
10380	.repo/project-objects/mbj4668/pyang.git
8664	.repo/project-objects/vyos/shim-signed.git
7196	.repo/project-objects/vyos/vyatta-bash.git
6372	.repo/project-objects/vyos/vyos.vyos.git
5164	.repo/project-objects/vyos/vyatta-cfg-system.git
5040	.repo/project-objects/vyos/vyatta-cfg-quagga.git
4592	.repo/project-objects/vyos/vyatta-cfg.git
3816	.repo/project-objects/vyos/vyos-walinuxagent.git
3112	.repo/project-objects/vyos/vyconf.git
3044	.repo/project-objects/vyos/vyos-workflow-test-temp.git
2900	.repo/project-objects/vyos/live-boot.git
2696	.repo/project-objects/vyos/vyos-vpp-patches.git
2620	.repo/project-objects/vyos/vyos-nightly-build.git
2476	.repo/project-objects/vyos/vyos1x-config.git
2444	.repo/project-objects/vyos/conntrack-tools.git
2108	.repo/project-objects/vyos/community.vyos.net.git
2036	.repo/project-objects/huihuimoe/vyos-arm64-build.git
1956	.repo/project-objects/vyos/libpam-radius-auth.git
1948	.repo/project-objects/vyos/vyatta-op.git
1804	.repo/project-objects/vyos/vyos-workflow-testing.git
1616	.repo/project-objects/vyos/vyos-cla-signatures.git
1564	.repo/project-objects/vyos/ipaddrcheck.git
1536	.repo/project-objects/vyos/vyos-utils.git
1452	.repo/project-objects/vyos/vyos-automation.git
1396	.repo/project-objects/vyos/vyos-vpp.git
1364	.repo/project-objects/vyos/libvyosconfig.git
1360	.repo/project-objects/vyos/vyos-http-api-tools.git
1176	.repo/project-objects/vyos/vyos-utils-misc.git
1164	.repo/project-objects/vyos/libtacplus-map.git
1144	.repo/project-objects/vyos/vyos-infrastructure.git
1128	.repo/project-objects/budimanjojo/vyos-config.git
1124	.repo/project-objects/vyos/vyatta-cfg-firewall.git
1104	.repo/project-objects/vyos/vyatta-biosdevname.git
1044	.repo/project-objects/vyos/libnss-mapuser.git
1028	.repo/project-objects/vyos/hvinfo.git
996	.repo/project-objects/vyos/vyatta-cfg-vpn.git
956	.repo/project-objects/vyos/libpam-tacplus.git
940	.repo/project-objects/vyos/mergify.git
928	.repo/project-objects/vyos/vyatta-cfg-qos.git
888	.repo/project-objects/vyos/shim-review.git
880	.repo/project-objects/vyos/vyos-github-actions.git
872	.repo/project-objects/vyos/libnss-tacplus.git
792	.repo/project-objects/vyos/vyatta-wanloadbalance.git
764	.repo/project-objects/vyos/initramfs-tools.git
608	.repo/project-objects/mbj4668/yang-mode.git
576	.repo/project-objects/vyos/tacplusd.git
552	.repo/project-objects/vyos/uncron.git
536	.repo/project-objects/vyos/vyatta-op-vpn.git
476	.repo/project-objects/vyos/MAC-Telnet.git
460	.repo/project-objects/vyos/pam_tacplus.git
440	.repo/project-objects/vyos/libmnl.git
436	.repo/project-objects/srl-labs/network-multitool.git
408	.repo/project-objects/vyos/vyatta-nat.git
400	.repo/project-objects/vyos/vyos-user-utils.git
384	.repo/project-objects/vyos/rest.vyos.git
376	.repo/project-objects/vyos/vyatta-conntrack.git
336	.repo/project-objects/vyos/udp-broadcast-relay.git
328	.repo/project-objects/vyos/vyos-opennhrp.git
328	.repo/project-objects/vyos/amplify-build-status.git
320	.repo/project-objects/yunzheng/vyos-arm64-iso.git
300	.repo/project-objects/vyos/ticket-app.git
284	.repo/project-objects/vyos/vyatta-op-firewall.git
276	.repo/project-objects/vyos/vyos-salt-minion.git
216	.repo/project-objects/vyos/vyos-world.git
216	.repo/project-objects/vyos/public-images.git
212	.repo/project-objects/vyos/vyatta-op-qos.git
212	.repo/project-objects/vyos/vyatta-cluster.git
208	.repo/project-objects/vyos/vyos.git
204	.repo/project-objects/vyos/vyos-community-flavors.git
204	.repo/project-objects/vyos/vyatta-config-mgmt.git
192	.repo/project-objects/mu-ruU1/vyos-build-container-image.git
184	.repo/project-objects/vyos/vyos-xe-guest-utilities.git
152	.repo/project-objects/vyos/vyos-nhrp.git
148	.repo/project-objects/vyos/vyatta-zone.git
144	.repo/project-objects/vyos/phorge-elasticsearch-modern.git
144	.repo/project-objects/vyos/openvpn-duo-plugin.git
140	.repo/project-objects/vyos/vyos-sdk.git
120	.repo/project-objects/vyos/vyos-community-process.git
116	.repo/project-objects/vyos/mirror-canary.git
112	.repo/project-objects/vyos/mdns-repeater.git
80	.repo/project-objects/vyos/gh-action-test.git
#+end_example

#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto
# could be dangerous if processes are writing to this
repo forall -c 'git gc --prune-now'
#+end_src

***** After

#+name: vyosDuAfter
#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto :cache yes
cd $repoproject
du -s **/* | sort -nr
#+end_src

#+RESULTS[6e8d8d9a69cc76927fcd3fc8639f67f20ef74785]: vyosDuAfter
#+begin_example
299628	vyos/vyos-documentation
223000	yang/yangsuite
120564	vyos/vyos-1x
51992	frr/tests
48396	vyos/vyos-build
21560	vyos/vyatta-bash
18644	vyos/zbackup_vyos-workflow-test-temp
15316	vyos/efi-boot-shim
13952	yang/pyang
11360	yang/libyang
9444	srl-labs/containerlab
8588	vyos/vyos.vyos
7892	vyos/vyos-cloud-init
6792	frr/bgpd
6228	frr/doc
4404	frr/lib
4140	vyos/shim-signed
3900	frr/zebra
2796	vyos/vyos-live-build
2492	frr/pimd
2256	frr/ospfd
1904	frr/isisd
1304	vyos/vyos-automation
1264	frr/tools
1240	vyos/rest.vyos
1224	vyos/vyatta-cfg
1188	frr/ospf6d
1044	frr/pceplib
908	frr/yang
852	vyos/live-boot
720	frr/ldpd
688	vyos/vyatta-cfg-system
656	vyos/vyconf
616	vyos/community.vyos.net
580	frr/pathd
536	vyos/vyatta-biosdevname
532	frr/eigrpd
512	frr/bfdd
492	vyos/libpam-tacplus
444	vyos/vyos-vpp-patches
428	vyos/libpam-radius-auth
376	frr/ripd
356	frr/staticd
336	vyos/vyos1x-config
332	frr/nhrpd
332	frr/mgmtd
316	frr/babeld
300	misc/budimanjojo
284	vyos/vyos-nightly-build
280	vyos/ipaddrcheck
276	misc/huihuimoe
264	frr/ripngd
252	frr/debian
236	frr/vtysh
220	frr/vrrpd
216	frr/include
208	frr/pbrd
200	misc/mu-ruU1
188	vyos/libnss-mapuser
188	frr/snapcraft
180	vyos/libtacplus-map
164	vyos/hvinfo
164	frr/docker
148	frr/python
136	frr/sharpd
128	vyos/phorge-elasticsearch-modern
124	vyos/vyos-utils-misc
124	frr/m4
112	frr/ospfclient
100	vyos/vyos-github-actions
100	vyos/mirror-canary
92	frr/redhat
92	frr/configure.ac
88	vyos/vyos-http-api-tools
84	vyos/vyos-infrastructure
80	frr/watchfrr
72	vyos/vyos-cla-signatures
60	srl-labs/network-multitool
56	misc/yunzheng
52	frr/gdb
44	vyos/mergify
44	frr/qpb
44	frr/pkgsrc
44	frr/fpm
28	frr/grpc
24	yang/yang-mode
24	frr/alpine
20	frr/mlag
12	frr/Makefile.am
8	vyos/gh-action-test
4	frr/version.h
4	frr/stamp-h.in
4	frr/README.md
4	frr/COPYING
4	frr/config.version.in
4	frr/buildtest.sh
4	frr/bootstrap.sh
#+end_example

#+name: vyosRepoDuAfter
#+begin_src shell :results output :var repoproject="vyos" :dir /data/ecto :cache yes
cd $repoproject
du -s .repo/project-objects/**/* | sort -nr
#+end_src

#+RESULTS[a64a8f78c42659781377f03ca1ac1f3efcbeb43a]: vyosRepoDuAfter
#+begin_example
89072	.repo/project-objects/vyos/vyos-documentation.git
82924	.repo/project-objects/frrouting/frr.git
81788	.repo/project-objects/srl-labs/containerlab.git
79432	.repo/project-objects/CiscoDevNet/yangsuite.git
70876	.repo/project-objects/vyos/infinitytier.git
33856	.repo/project-objects/vyos/gh-action-test-vyos-1x.git
25128	.repo/project-objects/vyos/vyos-strongswan.git
23520	.repo/project-objects/vyos/vyos-1x.git
23404	.repo/project-objects/CESNET/libyang.git
17912	.repo/project-objects/vyos/vyos-live-build.git
12064	.repo/project-objects/vyos/efi-boot-shim.git
10376	.repo/project-objects/vyos/vyos-build.git
9160	.repo/project-objects/vyos/vyos-cloud-init.git
8292	.repo/project-objects/mbj4668/pyang.git
7924	.repo/project-objects/vyos/shim-signed.git
5636	.repo/project-objects/vyos/vyatta-bash.git
5040	.repo/project-objects/vyos/vyatta-cfg-quagga.git
4124	.repo/project-objects/vyos/vyatta-cfg-system.git
3816	.repo/project-objects/vyos/vyos-walinuxagent.git
3044	.repo/project-objects/vyos/vyos-workflow-test-temp.git
2536	.repo/project-objects/vyos/vyatta-cfg.git
2444	.repo/project-objects/vyos/conntrack-tools.git
2340	.repo/project-objects/vyos/vyos.vyos.git
2036	.repo/project-objects/vyos/live-boot.git
1948	.repo/project-objects/vyos/vyatta-op.git
1804	.repo/project-objects/vyos/vyos-workflow-testing.git
1536	.repo/project-objects/vyos/vyos-utils.git
1396	.repo/project-objects/vyos/vyos-vpp.git
1364	.repo/project-objects/vyos/libvyosconfig.git
1124	.repo/project-objects/vyos/vyatta-cfg-firewall.git
996	.repo/project-objects/vyos/vyatta-cfg-vpn.git
928	.repo/project-objects/vyos/vyatta-cfg-qos.git
888	.repo/project-objects/vyos/shim-review.git
872	.repo/project-objects/vyos/libnss-tacplus.git
792	.repo/project-objects/vyos/vyatta-wanloadbalance.git
764	.repo/project-objects/vyos/initramfs-tools.git
756	.repo/project-objects/vyos/vyos-nightly-build.git
628	.repo/project-objects/vyos/community.vyos.net.git
592	.repo/project-objects/vyos/vyconf.git
576	.repo/project-objects/vyos/tacplusd.git
552	.repo/project-objects/vyos/uncron.git
536	.repo/project-objects/vyos/vyatta-op-vpn.git
516	.repo/project-objects/vyos/vyos-automation.git
476	.repo/project-objects/vyos/MAC-Telnet.git
464	.repo/project-objects/vyos/libpam-radius-auth.git
460	.repo/project-objects/vyos/pam_tacplus.git
440	.repo/project-objects/vyos/libmnl.git
408	.repo/project-objects/vyos/vyatta-nat.git
400	.repo/project-objects/vyos/vyos-user-utils.git
376	.repo/project-objects/vyos/vyatta-conntrack.git
360	.repo/project-objects/huihuimoe/vyos-arm64-build.git
336	.repo/project-objects/vyos/udp-broadcast-relay.git
328	.repo/project-objects/vyos/vyos-opennhrp.git
328	.repo/project-objects/vyos/amplify-build-status.git
320	.repo/project-objects/vyos/vyos1x-config.git
320	.repo/project-objects/vyos/vyatta-biosdevname.git
316	.repo/project-objects/vyos/rest.vyos.git
308	.repo/project-objects/vyos/vyos-vpp-patches.git
300	.repo/project-objects/vyos/ticket-app.git
284	.repo/project-objects/vyos/vyatta-op-firewall.git
280	.repo/project-objects/vyos/ipaddrcheck.git
276	.repo/project-objects/vyos/vyos-salt-minion.git
256	.repo/project-objects/budimanjojo/vyos-config.git
216	.repo/project-objects/vyos/vyos-world.git
216	.repo/project-objects/vyos/public-images.git
212	.repo/project-objects/vyos/vyatta-op-qos.git
212	.repo/project-objects/vyos/vyatta-cluster.git
208	.repo/project-objects/vyos/vyos.git
204	.repo/project-objects/vyos/vyos-community-flavors.git
204	.repo/project-objects/vyos/vyatta-config-mgmt.git
204	.repo/project-objects/vyos/libpam-tacplus.git
200	.repo/project-objects/mu-ruU1/vyos-build-container-image.git
188	.repo/project-objects/vyos/libnss-mapuser.git
188	.repo/project-objects/vyos/hvinfo.git
184	.repo/project-objects/vyos/vyos-xe-guest-utilities.git
176	.repo/project-objects/vyos/vyos-http-api-tools.git
172	.repo/project-objects/vyos/vyos-cla-signatures.git
152	.repo/project-objects/vyos/vyos-nhrp.git
148	.repo/project-objects/vyos/vyatta-zone.git
144	.repo/project-objects/vyos/phorge-elasticsearch-modern.git
144	.repo/project-objects/vyos/openvpn-duo-plugin.git
140	.repo/project-objects/vyos/vyos-sdk.git
140	.repo/project-objects/vyos/libtacplus-map.git
128	.repo/project-objects/vyos/mirror-canary.git
124	.repo/project-objects/vyos/vyos-infrastructure.git
124	.repo/project-objects/vyos/vyos-github-actions.git
124	.repo/project-objects/vyos/mergify.git
120	.repo/project-objects/vyos/vyos-utils-misc.git
120	.repo/project-objects/vyos/vyos-community-process.git
120	.repo/project-objects/srl-labs/network-multitool.git
112	.repo/project-objects/vyos/mdns-repeater.git
88	.repo/project-objects/mbj4668/yang-mode.git
80	.repo/project-objects/yunzheng/vyos-arm64-iso.git
76	.repo/project-objects/vyos/gh-action-test.git
#+end_example


*** Shell Scripts

Grok the general directory structure with =tree -dL 3 .= after submodules have
been modulized

#+begin_src shell :results output :var repoproject="crypto" :dir /data/ecto
cd $repoproject
repo forall  -c 'echo $REPO_LREV $REPO_RREV $REPO_PATH $REPO_PROJECT' | head -n7

echo -n '' # idk. it just be like that sometimes
#+end_src

#+RESULTS:
: 78571a281eb251e75683b345025ed74f8b5c6c54 refs/tags/gnupg-2.2.50 gnupg/gnupg-2.2 gnupg
: 9d302f978bd718a7b477294c2f5b386bea6ca00d refs/heads/STABLE-BRANCH-2-4 gnupg/gnupg-2.4 gnupg
: b39a0298112de853cc7c0833ed1c366330a225ef refs/tags/gnupg-2.5.13 gnupg/gnupg-2.5 gnupg
: d0d9652e402ede5824204cf2a8595a89d8f3f9ff refs/heads/master go/go-ykpiv go-piv/go-ykpiv
: 5a76b44bb2ea34ea4b24a6e295fc0a234f5f0692 refs/heads/master go/piv-go go-piv/piv-go
: f380bc1c902b4dcd2a134eadabdd2ecc5a38e211 refs/heads/dev pki/fpkilint gsa/fpkilint
: 64bbb446efa71a64f5cc23a6be94e58b909a6681 refs/heads/main python/cryptography pyca/cryptography

Available environment variables

| ~REPO_PROJECT~   | unique name of the project                                                                    |
| ~REPO_PATH~      | path relative to client root                                                                  |
| ~REPO_OUTERPATH~ | sub manifest's root path relative to client root                                              |
| ~REPO_INNERPATH~ | path relative to root of sub manifest                                                         |
| ~REPO_REMOTE~    | name of the remote system from manifest.                                                      |
| ~REPO_LREV~      | revision from the manifest, translated to a local tracking branch                             |
| ~REPO_RREV~      | revision from the manifest, exactly as written in manifest.                                   |
| ~REPO_COUNT~     | total number of projects being iterated.                                                      |
| ~REPO_I~         | 1-based iteration count ~REPO_I / REPO_COUNT~ shows progress                                    |
| ~REPO__*~        | extra environment variables, specified by the "annotation" element under any project element. |

+ use =REPO_LREV= if you need to pass the manifest revision to a locally executed
  git command
+ =REPO__*= can be useful for differentiating trees based on user-specific
  criteria, or simply annotating tree details

**** Touch repo roots

This will break as git & repo manipulate the repositories, but having remotely
accurate mtimes helps to hone in on what's recent.

#+name: repoTouchRoots
#+begin_src shell :results output :var repoproject="crypto" :dir /data/ecto :sync t
cd $repoproject
repo forall -e -c 'touch -m -d $(git log -1 --format="%ad" --date=iso-strict) .'

echo -n '' # idk. it just be like that sometimes
#+end_src

#+RESULTS: repoTouchRoots

Doesn't print anything, but it seems to work. =touch= will also appear to change
the =ctime=, which is apparently kinda hard to deal with (probably not but idk)

***** TODO add to a Makefile (and also touch parent directories)
probably needed one a long time ago.... dsakfdhskl. it doesn't run in a
checkout.... and you can't =repo init= to a parent-directory. :(

#+call: repoTouchRoots(repoproject="tensorflow")

#+RESULTS:

**** Maintain Manifests

Now that deltas are minimal (and XML's are guaranteed to be sorted/uniq), things
like this work.

#+begin_quote
I'm probably getting rid of this this submodules approach later. it's just messy
and no one's consuming these repos.

It's also not so great when signing commits.
#+end_quote

***** Validate

Check status

#+begin_src shell
git submodule foreach "git status -s"
#+end_src

Print gitignores

#+begin_src sh
find . -name .gitignore -type f -print \
    | xargs grep --color=auto -e  '^'

    # | xargs -n1 cat # this doesn't print the filename ... idk
#+end_src

***** Manage submodules

#+begin_quote
Quite a bit of this submodule stuff is a bit unwieldy, requiring manual
intervention. The distinct content and my updates are sparse.
#+end_quote

Pull updates and try to rebase local extant commits not persistified
upstream ... and don't checkout a dangling git reference.

#+begin_src shell
git submodule update --remote --rebase
#+end_src

Map =git stash/pull/pop= across submodules

#+begin_src shell
git submodule foreach "git stash && git pull origin master && git stash pop"
#+end_src

***** List submodules

#+begin_src shell
git config --file=.gitmodules submodule."blender".path
#+end_src

#+RESULTS:
: blender

I'm assuming the next command comports with the previous

#+name: ectorepoModules
#+begin_src shell :results output silent
srepo="$(pwd)"
git submodule foreach --quiet 'echo $(pwd)' | sed -E "s|$srepo/||g" | sort
#+end_src

All the =_remotes.xml= files

#+name: ectorepoRemotesXML
#+begin_src shell :results output silent
find . -mindepth 2 -maxdepth 2 -name "_remotes.xml" | cut -f2- -d'/' | sort
#+end_src

All the directories with =default.xml=

#+name: ectorepoDefaultXML
#+begin_src shell :results output silent
find . -mindepth 2 -maxdepth 2 -name "default.xml" | cut -f2- -d'/' | sort
#+end_src

The subprojects that aren't gitmodules

#+name: ectorepoNonModules
#+begin_src shell :results output silent :var modules=ectorepoModules defxml=ectorepoDefaultXML
comm -2 -3 <(echo $defxml | tr ' ' '\n' | cut -f1 -d'/' | sort) \
   <(echo $modules | tr ' ' '\n' | sort)
#+end_src

****** Misc

Which one sticks out?

#+begin_src shell :results output code :wrap example diff
diff <(find . -mindepth 2 -name "default.xml" | sort | cut -f2- -d'/') \
    <(grep -re _remotes.xml --include="default.xml" * | sort | cut -f1 -d':')
echo
#+end_src

#+RESULTS:
#+begin_example diff
4d3
< basic-sec/default.xml

#+end_example

***** Manage =_remotes.xml=

Consolidate =<remote ... />= nodes from all =_remote.xml= files and compare with the
top-level.

The red is missing from =$_REPO/_remote.xml= ...

+ something weird here: use the =git submodule foreach= below (EDIT: some
  non-module, uncommited repos lacked the remotes...)

#+begin_src shell :results output code :wrap example diff
cat  **/_remotes.xml | grep '<remote' | sort | uniq \
    | diff - <(grep '<remote ' _remotes.xml | sort | uniq)
echo
#+end_src

Again, but only for projects with modules

#+begin_src shell :results output code :wrap example diff :var modules=ectorepoModules
mremotes=$(find $modules -name _remotes.xml)
for m in $mremotes; do
    echo $m
    grep '<remote' $m | sort | uniq \
        | diff - <(grep '<remote ' _remotes.xml | sort | uniq)
done
#+end_src

****** Fan-out Copies of =_remotes.xml=

#+begin_src shell
git submodule foreach "cp ../_remotes.xml _remotes.xml"
#+end_src

Diff for lagging copies of =_remotes.xml= across submodules.

+ Diff outputs non-standard exit codes which breaks these macro commands and
  also org babel blocks.
+ The grep will only show the lines from files changed inside the submodule.
  Just a quick check... There's probably a better way with submodule tooling.

#+begin_src shell
git submodule --quiet foreach "diff ../_remotes.xml _remotes.xml ; echo ''" | grep -e '^>'
echo ' '
#+end_src

#+RESULTS:

****** Check, commit and push submodules

#+begin_src shell
git submodule foreach "git add _remotes.xml"
git status
git submodule foreach "git diff --color" # | less
git submodule foreach "git status" # just to be sure
git submodule foreach "git commit -m 'bump remotes.xml'"
git submodule foreach "git push origin master"

# && add the um modules... todo
#+end_src

Then in magit, add submodule refs, commit to super-duper-project and push

... then pull again maybe (reference copies be on a server with SSH access)
***** And so forth

**** Old Merge =_remotes.xml= Manifests

I'm not sure how to merge patches while dropping file source info. This just
finds and reports all lines not in the top-level manifest.

#+begin_src shell :results output
allremotes=_remotes.xml
subremotes=(*/_remotes.xml)

mergedir=$(mktemp -d)

echo $mergedir

for remote in "${subremotes[@]}";do
    remotename=$(dirname $remote)
    #echo "diff $allremotes $remote > remote.diff"
    diff $allremotes $remote > $mergedir/$remotename.xml
done

cat $mergedir/* | grep -e "^>\s*<remote" | sort | uniq | cut -b2-
#+end_src

#+RESULTS:
#+begin_example
/tmp/tmp.6eUYYdLkTz
   <remote name="framagit" fetch="https://framagit.org"/>
   <remote name="github" fetch="https://github.com"/>
   <remote name="srht_abcdw" fetch="https://git.sr.ht/~abcdw"/>
   <remote name="srht_akagi" fetch="https://git.sr.ht/~akagi"/>
   <remote name="srht_krevedkokun" fetch="https://git.sr.ht/~krevedkokun"/>
   <remote name="srht_michal_atlas" fetch="https://git.sr.ht/~michal_atlas"/>
   <remote name="srht_plattfot" fetch="https://git.sr.ht/~plattfot"/>
   <remote name="srht_sircmpwn" fetch="https://git.sr.ht/~sircmpwn"/>
   <remote name="srht_whereiseveryone" fetch="https://git.sr.ht/~whereiseveryone"/>
#+end_example

**** Commit Missing Remotes

After copying updated =_remotes.xml=

#+begin_src shell :results output

remotefile=_remotes.xml
subremotes=(*/_remotes.xml)
currentdir=$(pwd)

for remote in "${subremotes[@]}"; do
subdir=$(dirname $remote)
cd $subdir
git add $remotefile
# script will quit on first error
# git commit -m "update $remotefile"
cd $currentdir
done
#+end_src

#+RESULTS:
*** Python Scripts

When provided the above manifest, a vanilla =buffer-env= configuration, permits
hacking on the python scripts using commands like:

+ C-c C-p :: run-python
+ C-c C-c :: python-shell-send-buffer

Repo's =XmlManifest= class requires a =repodir= and =manifest_file= path. for
these scripts below, I assume that the script is running from =$_REPO= and that
the manifests are sync'd into =$_ECTO/$project=.

**** Merge Manifests

#+begin_src shell
guix shell -m manifest.scm -- python util/merge_manifests.py
#+end_src

#+RESULTS:

#+begin_src python :tangle util/merge_manifests.py  :tangle-mode (identity #o744) :mkdirp yes
import sys
import os
import glob
from os.path import join

import manifest_xml
#from manifest_xml import *
#from manifest_xml import GitcManifest
#from manifest_xml import XmlManifest, GitcManifest, GitcClient
#from manifest_xml import GitcManifest, RepoClient

ecto_dir = os.environ["_ECTO"]
repo_dir = os.environ["_REPO"]
template = join(repo_dir, "_remotes.xml")

remotes_xml_files = glob.glob("*/_remotes.xml")
repo_names = list(map(lambda p: p.split("/")[0], remotes_xml_files))
ecto_paths = list(map(lambda n: "/".join([ecto_dir,n]), repo_names))

#ecto_manifests = list(map(lambda i: GitcManifest(ecto_paths[i], remotes_xml_files[i]),
#                          range(len(remotes_xml_files))))
ecto_manifests = list(map(lambda i: RepoClient(ecto_paths[i], remotes_xml_files[i]),
                          range(len(remotes_xml_files))))

#print(ecto_manifests[0].remotes)
#repo_remote_xml = GitcManifest(".", "_remotes.xml")
#print(repo_remote_xml.remotes)
print(template)
#+end_src

#+RESULTS:

#+begin_example python

# def output_manifest(file):

# assume that the immediate subdirectories of dir may contain _remotes.xml
# collect these files into a list

# def consolidate_remotes(dir):
# os.walk

print(os.path)
print(__file__)

def main(orig_args):
    print("orig_args:",orig_args)

if __name__ == '__main__':
  main(sys.argv[1:])

#+end_example


** Repo Checkout Tools

*** Fix misbehaving checkouts

Running =repo sync= and cloning too many bundles at once ends up not updating
the =pwd= with checkouts, which makes running manual =repo sync $project= a bit
difficult.

#+name: superproject
#+begin_src emacs-lisp :results replace value
"tensorflow"
#+end_src

#+name: superinclude
#+begin_src emacs-lisp :results replace value
"tensorflow_core.xml"
#+end_src

#+name: projects
#+header:  :var superproject=superproject superinclude=superinclude
#+begin_src sh :results replace output
grep -e '<project' $_REPO/$superproject/$superinclude | sed -E 's/^.*path="(.*)" ref=".*$/\1/'
#+end_src

#+RESULTS: projects
#+begin_example
.allstar
adanet
addons
agents
benchmarks
build
cloud
codelabs
community
compression
custom-op
data-validation
datasets
decision-forests
deepmath
docs
docs-l10n
dtensor-gcp-examples
ecosystem
embedding-projector-standalone
estimator
examples
fairness-indicators
federated
fold
gan
gnn
graphics
haskell
hub
io
java
java-models
java-ndarray
kfac
lattice
lingvo
lucid
mesh
metadata
mlir-hlo
model-analysis
model-card-toolkit
model-optimization
model-remediation
models
networking
neural-structured-learning
nmt
oss-fuzz
playground
privacy
probability
profiler
profiler-ui
quantum
ranking
recommenders
recommenders-addons
runtime
rust
serving
sig-tfjs
similarity
swift-apis
tcav
tensor2tensor
tensorboard
tensorflow
tensorrt
text
tf-build-actions
tfhub.dev
tfjs
tfjs-examples
tfjs-models
tfjs-website
tfjs-wechat
tflite-micro
tflite-micro-arduino-examples
tflite-support
tfx
tfx-addons
tfx-bsl
toolchains
tpu
transform
#+end_example

** Git
