#+title:     Ectorepo: NixOS
#+author:    David Conner
#+email:     noreply@te.xel.io
#+PROPERTY: header-args :comments none

When using =repo init -u $url -m $manifest= instead of the git submodule to
checkout, the filepaths for =<include name=mnfst.xml/>= are relative to the root
repository.

#+begin_src xml :tangle default.xml
<manifest>
  <include name="_remotes.xml"/>
  <default remote="github" sync-j="8" revision="refs/heads/master"/>
  <include name="nixos/nixos.xml"/>
  <include name="nixos/nixcommunity.xml"/>
  <include name="nixos/numtide.xml"/>
  <include name="nixos/flakes.xml"/>
</manifest>
#+end_src

* NixOS Repos

Networking

+ [[https://github.com/oddlama/nix-topology?tab=readme-ov-file][oddlama/nix-topology]] looks fantastic 4 homelab

Infra

+ [[https://primamateria.github.io/blog/hive/][PrimaMateria's Hive]] (blog on)

Security

+ [[https://github.com/cynicsketch/nix-mineral][cynicsketch/nix-mineral]]

CLI

+ [[https://github.com/utdemir/nix-tree][utdemir/nix-tree]]
+ nix-visualise

** Numtide

A lot of interesting devops/consulting-oriented repos:

+ [[https://github.com/numtide/software-consulting-documents][numtide/software-consulting-documents]] :: copyright-free? as in ... Patron's on
  me?
+ [[https://github.com/numtide/deploy-kit][numtide/deploy-kit]] :: lightweight Ansible bc why not write your own Nornir?
+ [[https://github.com/numtide/generate-terraform-provider-shim][numtide/software-consulting-documents]]
+ [[https://github.com/numtide/action-cli][numtide/action-cli]]
+ [[https://github.com/numtide/nits][numtide/nits]] :: nix + [[https://docs.nats.io/?_gl=1*16na8r0*_ga*ODgyMTUzOTYxLjE3NTQ5MDgwNjU.*_ga_6242VH03CH*czE3NTQ5MDgwNjQkbzEkZzAkdDE3NTQ5MDgwNjgkajU2JGwwJGgw][nats]]: open source data layer for IoT messaging,
  cloud-native applications & +microservices+.
  - share state between services. Jetstream provides the persistence layer.
  - "when you need lower-level access to persistence streams", move on to using
    [[https://github.com/nats-io/nats.docs/blob/master/nats-concepts/jetstream/README.md][JetStream]] directly "for more advanced messaging patterns"
+ [[https://github.com/numtide/NixOS-Fleet-Update-Provider][numtide/NixOS-Fleet-Update-Provider​]]



* Repo Setup
** Babel Setup

Check rates:

#+begin_src emacs-lisp :results value code :exports code
(ghub-graphql-rate-limit)
#+end_src

To avoid confirmations

#+begin_src emacs-lisp
(setq-local org-confirm-babel-evaluate nil
            org-table-convert-region-max-lines 9999)
#+end_src


#+name: nrepos
#+begin_src emacs-lisp
100
#+end_src

#+RESULTS: nrepos
: 100

** Flakes

#+begin_src xml :tangle flakes.xml :noweb yes
<manifest>
  <!-- flakes/snippets -->
  <project name="mrVanDalo/flake-templates" path="flakes/snippets/flake-templates" revision="refs/heads/main" remote="github"/>
  <!-- flakes/lib -->
  <project name="Lunarnovaa/LunarsLib" path="flakes/lib/lunarslib" revision="refs/heads/main" remote="github"/>
  <!-- security -->
  <project name="cynicsketch/nix-mineral" path="sec/nix-mineral" revision="refs/heads/main" remote="github"/>
  <project name="schizofox/schizofox" path="sec/schizofox" revision="refs/heads/main" remote="github"/>
  <project name="schizofox/searx-randomizer" path="sec/searx-randomizer" revision="refs/heads/main" remote="github"/>
  <!-- secrets -->
  <project name="Mic92/sops-nix" path="secrets/sops-nix" revision="refs/heads/master" remote="github"/>
  <!-- dev -->
  <project name="tweag/jupyenv" path="dev/jupyenv" revision="refs/heads/main" remote="github"/>
  <!-- learn -->
  <project name="tweag/nix-hour" path="learn/nix-hour" revision="refs/heads/master" remote="github"/>
  <!-- tools/nix -->
  <project name="tweag/nixtract" path="tools/nix/nixtract" revision="refs/heads/main" remote="github"/>
  <!-- containers -->
  <project name="SEIAROTg/quadlet-nix" path="cni/quadlet-nix" revision="refs/heads/main" remote="github"/>
  <!-- vm -->
  <project name="Mic92/nixos-shell" path="vm/nixos-shell" revision="refs/heads/main" remote="github"/>
  <!-- platforms -->
  <project name="cleverca22/not-os" path="platforms/not-os" groups="nixos" revision="refs/heads/master"/>
  <!-- systems -->
  <project name="cloudripper/NixLFS" path="systems/NixLFS" groups="nixos" revision="refs/heads/main"/>
  <!-- iot -->
  <project name="cleverca22/rpi-nixos-example" path="iot/rpi-nixos-example" groups="nixos" revision="refs/heads/master"/>
  <project name="ElvishJerricco/rpi5-uefi-nix" path="iot/rpi5-uefi-nix" groups="nixos" revision="refs/heads/main"/>
  <project name="gnull/nixos-rk3588" path="iot/rockchip/nixos-rk3588" groups="nixos" revision="refs/heads/main"/>
  <project name="ryan4yin/nixos-config-sbc" path="iot/rockchip/nixos-config-sbc" groups="nixos" revision="refs/heads/main"/>
  <project name="phaitonican/orangepi5b-flake" path="iot/rockchip/orangepi5b-flake" groups="nixos" revision="refs/heads/main"/>
  <!-- boot -->
  <project name="Tow-Boot/Tow-Boot" path="boot/Tow-Boot" revision="refs/heads/development" remote="github"/>
  <!-- networking -->
  <project name="oddlama/nix-topology" path="net/nix-topology" revision="refs/heads/main" remote="github"/>
  <project name="divnix/std" path="net/std" revision="refs/heads/main" remote="github"/>
  <!-- hardware -->
  <project name="aws/uefi" path="hardware/uefi" revision="refs/heads/main" remote="github"/>
  <!-- home -->
  <project name="feel-co/hjem" path="home/hjem" revision="refs/heads/main" remote="github"/>
  <project name="snugnug/hjem-rum" path="home/hjem-rum" revision="refs/heads/main" remote="github"/>
  <project name="Rexcrazy804/hjem-impure" path="home/hjem-impure" revision="refs/heads/master" remote="github"/>
  <!-- hive -->
  <project name="PrimaMateria/nixos-hive" path="hive/nixos-hive" revision="refs/heads/main" remote="github"/>
  <project name="PrimaMateria/blog-hive" path="hive/blog-hive" revision="refs/heads/main" remote="github"/>
  <project name="divnix/hive" path="hive/hive" revision="refs/heads/main" remote="github"/>
  <!-- clan -->
  <project name="clan-lol/clan-core" path="clan/clan-core" revision="refs/heads/main" remote="github"/>
  <project name="clan-lol/clan-infra" path="clan/clan-infra" revision="refs/heads/main" remote="github"/>
  <project name="clan-lol/nix-select" path="clan/nix-select" revision="refs/heads/main" remote="github"/>
  <project name="mrVanDalo/clan-vars-generators" path="clan/clan-vars-generators" revision="refs/heads/main" remote="github"/>
</manifest>
#+end_src

** Nixos

Clone bundle sizes

#+name: fetchMetadata
#+headers: :var gh-org="FreeCAD" :jq-args "--raw-output" :eval query :results table
#+begin_src restclient :jq "sort_by(-.size) | map([.owner.login, .name, .size, .default_branch, .archived, .updated_at])[] | @csv"
:gh-graphql-url = https://api.github.com/graphql
:gh-url-base = https://api.github.com
:gh-url-path = orgs/:gh-org/repos
:gh-token := (auth-source-pass-get 'secret "api.github.com/dcunited001^ghub")

:headers = <<
Accept: application/vnd.github+json
Authorization: Bearer :gh-token
X-GitHub-Api-Version: 2022-11-28
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:138.0) Gecko/20100101 Firefox/138.0
# User-Agent: dcunited001 # um okay that doesn't work
# https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#user-agent

GET :gh-url-base/:gh-url-path
:headers
#+end_src

#+RESULTS: fetchMetadata

#+name: nixosMetadata
#+call: fetchMetadata(gh-org="nixos")

#+RESULTS: nixosMetadata
| NixOS | cabal2nix             |    3380 | master         | false | 2025-08-04T17:50:56Z |
| NixOS | distribution-nixpkgs  |     103 | moved          | true  | 2024-02-27T09:35:22Z |
| NixOS | foundation            |    2782 | master         | false | 2025-08-06T11:07:01Z |
| NixOS | hackage-db            |     106 | moved          | true  | 2024-02-27T09:35:25Z |
| NixOS | hydra                 |   16613 | master         | false | 2025-08-07T15:30:02Z |
| NixOS | hydra-ant-logger      |    1456 | master         | true  | 2024-02-27T09:34:46Z |
| NixOS | hydra-provisioner     |      15 | master         | true  | 2025-01-10T10:11:16Z |
| NixOS | infra                 |    7586 | main           | false | 2025-08-08T14:42:11Z |
| NixOS | jailbreak-cabal       |      47 | master         | false | 2025-07-17T16:11:33Z |
| NixOS | language-nix          |      95 | moved          | true  | 2024-02-27T09:35:30Z |
| NixOS | mvn2nix-maven-plugin  |     181 | master         | true  | 2024-11-25T11:31:28Z |
| NixOS | nix                   |  124094 | master         | false | 2025-08-08T23:48:30Z |
| NixOS | nix.dev               |    2084 | master         | false | 2025-08-08T23:08:10Z |
| NixOS | nix-eclipse           |   16600 | master         | true  | 2024-08-22T13:40:53Z |
| NixOS | nix-mode              |     561 | master         | false | 2025-08-05T16:04:44Z |
| NixOS | nixops                |    7013 | master         | false | 2025-08-08T05:49:57Z |
| NixOS | nixops-dashboard      |       0 | master         | false | 2023-02-16T19:24:11Z |
| NixOS | nixos                 |   14670 | master         | true  | 2025-06-08T20:06:59Z |
| NixOS | nixos-artwork         |  616120 | master         | true  | 2025-08-05T12:25:15Z |
| NixOS | nixos-channel-scripts |     246 | master         | false | 2025-07-21T14:48:11Z |
| NixOS | nixos-hardware        |    2431 | master         | false | 2025-08-07T14:14:07Z |
| NixOS | nixos-homepage        |   35294 | main           | false | 2025-08-08T18:20:51Z |
| NixOS | nixos-weekly          |    1231 | master         | true  | 2024-12-29T00:36:28Z |
| NixOS | nixpart               |     104 | master         | true  | 2025-07-06T02:50:13Z |
| NixOS | nixpkgs               | 5490317 | master         | false | 2025-08-08T23:44:38Z |
| NixOS | nixpkgs-channels      |  786893 | nixos-unstable | true  | 2025-06-05T18:07:17Z |
| NixOS | npm2nix               |     150 | master         | true  | 2024-08-09T19:36:19Z |
| NixOS | package-list          |      37 | master         | true  | 2024-02-27T09:35:15Z |
| NixOS | patchelf              |    1245 | master         | false | 2025-08-07T08:04:59Z |
| NixOS | systemd               |  123696 | nixos-v230     | true  | 2023-02-16T19:23:49Z |

Excluded Repositories

#+NAME: nixosReposExclude
| .github                        |
| first-time-contribution-tagger |
| hackage-db                     |
| hydra-ant-logger               |
| images                         |
| language-nix                   |
| mobile-nix-website             |
| moderation                     |
| mvn2nix-maven-plugin           |
| nix-constitutional-assembly    |
| nix-eclipse                    |
| nixops-dashboard               |
| nixos                          |
| nixos-artwork                  |
| nixos-weekly                   |
| nixpart                        |
| rfc-steering-committee         |
| sc-election-2024               |
| surveys                        |
| systemd                        |
| teams-collaboration            |
| whats-new-in-nix               |


** Nixos Repos

#+name: nixosRepos
#+begin_src emacs-lisp :var nrepos=60 :results replace vector value :exports code :noweb yes
(ghub-graphql
 (graphql-query ((organization
                  :arguments ((login . "nixos"))
                  (repositories
                   :arguments ((first . <<nrepos()>>)
                               (orderBy . ((field . UPDATED_AT)
                                           (direction . DESC))))
                   (edges
                    (node (owner login)
                          name
                          (defaultBranchRef prefix name)
                          url
                          updatedAt
                          isArchived)))))))
#+end_src

#+name: nixosReposXML
#+begin_src emacs-lisp :var gqldata=nixosRepos repos-exclude=nixosReposExclude :results value html
(setq -gql-data gqldata)

;; no repos-core variable
;; (repos-core (flatten-list repos- core))

(let* ((repos-exclude (flatten-list repos-exclude)))
  (thread-first
    (thread-last
      (a-get* (nthcdr 0 gqldata) 'data 'organization 'repositories 'edges)
      (mapcar (lambda (el) (a-get* el 'node)))

      ;; filter archived repos
      (seq-filter (lambda (el) (not (a-get* el 'isArchived))))

      ;; filter repos in reposExclude list
      (seq-filter (lambda (el) (not (member (a-get* el 'name) repos-exclude))))
      (mapcar (lambda (el)
                (let* ((raw-name (a-get* el 'name))

                       ;; (repo-core? (member raw-name repos-core))

                       (path-dirs (list "nixos" raw-name))

                       ;; (path-dirs (cond (repo-core? (list "core" raw-name))
                       ;;                 (t (list "misc" raw-name))))

                       (path (string-join path-dirs "/"))
                       (ref (concat (a-get* el 'defaultBranchRef 'prefix)
                                    (a-get* el 'defaultBranchRef 'name)))
                       (name (string-join (list (a-get* el 'owner 'login)
                                                (a-get* el 'name)) "/")))
                  (concat "<project"
                          " name=\"" name
                          "\" path=\"" path
                          "\" revision=\"" ref "\" remote=\"github\"/>")))))
    (cl-sort 'string-lessp :key 'downcase)
    (string-join "\n")))
#+end_src

#+RESULTS: nixosReposXML

*** Generate XML

Generate =nixos.xml=

#+begin_src xml :tangle nixos.xml :noweb yes
<manifest>
  <<nixosReposXML()>>
</manifest>
#+end_src
** nix-community

#+name: nixcommunityMetadata
#+call: fetchMetadata(gh-org="nix-community")

#+RESULTS: nixcommunityMetadata
| nix-community | NUR                   | 162654 | main   | false | 2025-08-08T21:54:14Z |
| nix-community | home-manager          | 109413 | master | false | 2025-08-08T23:37:49Z |
| nix-community | pypi2nix              |  33671 | master | true  | 2025-06-05T18:07:08Z |
| nix-community | luarocks-nix          |  12588 | master | false | 2025-04-09T03:52:26Z |
| nix-community | todomvc-nix           |  10130 | master | false | 2025-07-16T21:02:18Z |
| nix-community | vulnix                |   4050 | master | false | 2025-08-08T17:02:38Z |
| nix-community | nixbox                |   1668 | master | false | 2025-07-25T14:01:11Z |
| nix-community | nix-bundle            |   1478 | master | false | 2025-08-08T06:01:07Z |
| nix-community | emacs2nix             |   1251 | master | false | 2025-04-05T16:15:40Z |
| nix-community | nix-emacs             |    986 | master | false | 2025-06-27T17:12:51Z |
| nix-community | nixpkgs-update        |    941 | main   | false | 2025-08-07T14:14:03Z |
| nix-community | yarn2nix              |    814 | master | true  | 2025-08-03T04:49:47Z |
| nix-community | nix-index             |    510 | master | false | 2025-08-08T18:57:54Z |
| nix-community | builtwithnix.org      |    438 | master | false | 2025-07-08T21:11:35Z |
| nix-community | nixos-generators      |    333 | master | false | 2025-08-08T19:16:26Z |
| nix-community | pip2nix               |    320 | master | false | 2025-08-06T04:47:44Z |
| nix-community | setup.nix             |    319 | master | true  | 2023-06-25T18:32:53Z |
| nix-community | bundix                |    313 | master | false | 2025-08-01T23:33:03Z |
| nix-community | pnpm2nix              |    295 | master | false | 2025-07-26T08:43:30Z |
| nix-community | nix-zsh-completions   |    202 | master | false | 2025-08-05T21:06:20Z |
| nix-community | nur-packages-template |    162 | main   | false | 2025-08-01T18:03:23Z |
| nix-community | nixGL                 |    122 | main   | false | 2025-08-08T23:48:13Z |
| nix-community | mavenix               |    120 | master | false | 2025-05-03T14:55:21Z |
| nix-community | acpi_call             |    112 | master | false | 2025-08-03T07:09:46Z |
| nix-community | linuxkit-nix          |     91 | master | true  | 2025-02-16T06:26:55Z |
| nix-community | nur-update            |     65 | main   | false | 2025-07-28T20:45:59Z |
| nix-community | vagrant-nixos-plugin  |     50 | master | false | 2025-02-21T23:00:57Z |
| nix-community | docker-nix            |     40 | master | true  | 2024-12-12T08:14:38Z |
| nix-community | google-summer-of-code |     29 | master | true  | 2024-02-12T04:12:26Z |
| nix-community | wiki                  |     11 | master | true  | 2025-06-15T17:51:28Z |

Excluded Repositories

#+NAME: nixcommunityReposExclude
| .github                    |
| all-cabal-json             |
| bundix                     |
| composer-local-repo-plugin |
| dream2nix-auto-test        |
| eask2nix                   |

#+name: nixcommunityRepos
#+begin_src emacs-lisp :var nrepos=60 :results replace vector value :exports code :noweb yes
(ghub-graphql
 (graphql-query ((organization
                  :arguments ((login . "nix-community"))
                  (repositories
                   :arguments ((first . <<nrepos()>>)
                               (orderBy . ((field . UPDATED_AT)
                                           (direction . DESC))))
                   (edges
                    (node (owner login)
                          name
                          (defaultBranchRef prefix name)
                          url
                          updatedAt
                          isArchived)))))))
#+end_src

#+name: nixcommunityReposXML
#+begin_src emacs-lisp :var gqldata=nixcommunityRepos repos-exclude=nixcommunityReposExclude :results value html
(setq -gql-data gqldata)

;; no repos-core variable
;; (repos-core (flatten-list repos- core))

(let* ((repos-exclude (flatten-list repos-exclude)))
  (thread-first
    (thread-last
      (a-get* (nthcdr 0 gqldata) 'data 'organization 'repositories 'edges)
      (mapcar (lambda (el) (a-get* el 'node)))

      ;; filter archived repos
      (seq-filter (lambda (el) (not (a-get* el 'isArchived))))

      ;; filter repos in reposExclude list
      (seq-filter (lambda (el) (not (member (a-get* el 'name) repos-exclude))))
      (mapcar (lambda (el)
                (let* ((raw-name (a-get* el 'name))

                       ;; (repo-core? (member raw-name repos-core))

                       (path-dirs (list "nix-community" raw-name))

                       ;; (path-dirs (cond (repo-core? (list "core" raw-name))
                       ;;                 (t (list "misc" raw-name))))

                       (path (string-join path-dirs "/"))
                       (ref (concat (a-get* el 'defaultBranchRef 'prefix)
                                    (a-get* el 'defaultBranchRef 'name)))
                       (name (string-join (list (a-get* el 'owner 'login)
                                                (a-get* el 'name)) "/")))
                  (concat "<project"
                          " name=\"" name
                          "\" path=\"" path
                          "\" revision=\"" ref "\" remote=\"github\"/>")))))
    (cl-sort 'string-lessp :key 'downcase)
    (string-join "\n")))
#+end_src

*** Generate XML

Generate =nixcommunity.xml=

#+begin_src xml :tangle nixcommunity.xml :noweb yes
<manifest>
  <<nixcommunityReposXML()>>
</manifest>
#+end_src

** Numtide

#+name: numtideMetadata
#+call: fetchMetadata(gh-org="numtide")

#+RESULTS: numtideMetadata
| numtide | action-cli                       |      52 | main   | false | 2025-02-01T18:56:50Z |
| numtide | cert-wizard                      |      39 | main   | false | 2025-06-19T19:36:55Z |
| numtide | clean-git-action                 |      55 | main   | false | 2025-06-19T19:37:29Z |
| numtide | devshell                         |    1532 | main   | false | 2025-08-10T08:44:09Z |
| numtide | docker-host-forwarder            |       3 | main   | false | 2024-07-26T18:05:57Z |
| numtide | flake-utils                      |     113 | main   | false | 2025-08-06T21:28:37Z |
| numtide | freelancer-toolbox               |     318 | main   | false | 2025-07-16T21:26:42Z |
| numtide | generate-terraform-provider-shim |      50 | main   | false | 2025-06-18T02:10:35Z |
| numtide | .github                          |      17 | main   | false | 2025-03-18T21:49:03Z |
| numtide | github-deploy                    |    7072 | main   | false | 2025-03-18T17:31:02Z |
| numtide | kuta                             |    2151 | master | true  | 2023-01-28T05:06:21Z |
| numtide | nar-serve                        |     393 | main   | false | 2025-05-03T06:14:01Z |
| numtide | nix-eval-cache                   |      24 | main   | false | 2025-04-24T16:02:28Z |
| numtide | nix-filter                       |      63 | main   | false | 2025-08-06T13:42:24Z |
| numtide | nix-gitignore                    |       8 | master | true  | 2023-03-02T04:15:10Z |
| numtide | nix-parallel-test-case           |      50 | master | true  | 2023-01-28T15:55:52Z |
| numtide | nixpkgs                          | 3783551 | master | false | 2024-06-17T07:01:00Z |
| numtide | nixpkgs-unfree                   |     379 | main   | false | 2025-07-28T18:15:44Z |
| numtide | numtide.github.io                |       4 | main   | false | 2024-06-17T06:58:31Z |
| numtide | serve-go                         |      48 | main   | false | 2025-03-18T17:31:02Z |
| numtide | software-consulting-documents    |      45 | main   | false | 2023-07-07T13:19:09Z |
| numtide | terraform-deploy-nixos-flakes    |      10 | main   | false | 2025-03-18T17:31:02Z |
| numtide | terraform-linuxbox-monitorpack   |      37 | main   | false | 2025-03-18T17:31:02Z |
| numtide | terraform-linuxbox-traefik       |       6 | main   | false | 2025-03-18T17:31:02Z |
| numtide | terraform-nix-build              |       3 | main   | false | 2024-06-17T06:58:30Z |
| numtide | terraform-nixos-amis             |      14 | main   | false | 2025-03-18T21:49:02Z |
| numtide | terraform-provider-linuxbox      |     301 | main   | false | 2025-04-01T01:51:46Z |
| numtide | terraform-provider-secret        |    8273 | main   | false | 2023-07-01T17:03:48Z |
| numtide | treefmt                          |    3703 | main   | false | 2025-08-11T08:05:26Z |
| numtide | yarnlock2json                    |      13 | master | true  | 2023-01-28T18:27:03Z |

Excluded Repositories

#+NAME: numtideReposExclude
| .github                   |
| cert-wizard               |
| docker-host-forwarder     |
| go-nix                    |
| hwinfo                    |
| linux-lkl                 |
| matterircd                |
| nixmodules                |
| nixpkgs                   |
| activate                  |
| nix-stdlib                |
| numtide.github.io         |
| OpenGen.nix               |
| pro-spec                  |
| terraform-nix-build       |
| terraform-provider-secret |
| terraform-upload-ami      |

#+name: numtideRepos
#+begin_src emacs-lisp :var nrepos=60 :results replace vector value :exports code :noweb yes
(ghub-graphql
 (graphql-query ((organization
                  :arguments ((login . "numtide"))
                  (repositories
                   :arguments ((first . <<nrepos()>>)
                               (orderBy . ((field . UPDATED_AT)
                                           (direction . DESC))))
                   (edges
                    (node (owner login)
                          name
                          (defaultBranchRef prefix name)
                          url
                          updatedAt
                          isArchived)))))))
#+end_src

#+name: numtideReposXML
#+begin_src emacs-lisp :var gqldata=numtideRepos repos-exclude=numtideReposExclude :results value html
(setq -gql-data gqldata)

;; no repos-core variable
;; (repos-core (flatten-list repos- core))

(let* ((repos-exclude (flatten-list repos-exclude)))
  (thread-first
    (thread-last
      (a-get* (nthcdr 0 gqldata) 'data 'organization 'repositories 'edges)
      (mapcar (lambda (el) (a-get* el 'node)))

      ;; filter archived repos
      (seq-filter (lambda (el) (not (a-get* el 'isArchived))))

      ;; filter repos in reposExclude list
      (seq-filter (lambda (el) (not (member (a-get* el 'name) repos-exclude))))
      (mapcar (lambda (el)
                (let* ((raw-name (a-get* el 'name))

                       ;; (repo-core? (member raw-name repos-core))

                       (path-dirs (list "numtide" raw-name))

                       ;; (path-dirs (cond (repo-core? (list "core" raw-name))
                       ;;                 (t (list "misc" raw-name))))

                       (path (string-join path-dirs "/"))
                       (ref (concat (a-get* el 'defaultBranchRef 'prefix)
                                    (a-get* el 'defaultBranchRef 'name)))
                       (name (string-join (list (a-get* el 'owner 'login)
                                                (a-get* el 'name)) "/")))
                  (concat "<project"
                          " name=\"" name
                          "\" path=\"" path
                          "\" revision=\"" ref "\" remote=\"github\"/>")))))
    (cl-sort 'string-lessp :key 'downcase)
    (string-join "\n")))
#+end_src

*** Generate XML

Generate =numtide.xml=

#+begin_src xml :tangle numtide.xml :noweb yes
<manifest>
  <<numtideReposXML()>>
</manifest>
#+end_src
