#+title:     Ectorepo: FRC
#+author:    David Conner
#+email:     noreply@te.xel.io
#+PROPERTY: header-args+ :comments none

A list of repositories related to the FRC robotics competitions.

When using =repo init -u $url -m $manifest= instead of the git submodule to
checkout, the filepaths for =<include name=mnfst.xml/>= are relative to the root
repository.

* Manifest

#+begin_src xml :tangle default.xml
<manifest>
  <include name="_remotes.xml"/>
  <default remote="github" sync-j="8" revision="refs/heads/master"/>
  <include name="frc/wpilibsuite.xml"/>
  <include name="frc/robotpy.xml"/>
  <include name="frc/frcmisc.xml"/>
  <include name="frc/photonvision.xml"/>
  <!-- wpilibsuite,robotpy,frcmisc: 4GB (4/15/2025) -->
  <include name="frc/teams.xml"/>
  <include name="frc/bbFrc.xml"/>
  <include name="frc/ctre.xml"/>
  <include name="frc/hardware.xml"/>
  <include name="frc/lumyn.xml"/>
</manifest>
#+end_src

** Babel Setup

To avoid confirmations

#+begin_src emacs-lisp
(setq-local org-confirm-babel-evaluate nil)
#+end_src

Load blocks

#+begin_src emacs-lisp
;; untested
(org-babel-lob-ingest "../babel.org")
#+end_src

#+RESULTS:
: 1

Check rates with =ghubCheckRates()=

#+call: ghubCheckRates()

#+RESULTS:
#+begin_src emacs-lisp
5000
#+end_src

* Core

* Misc

The paths for the repositories here will change as I become more familiar with
the FRC ecosystem.


Generate =wpilibsuite.xml=

#+begin_src xml :tangle frcmisc.xml :noweb yes
<manifest>
  <!-- ./pathplanner -->
  <project name="mjansen4857/pathplanner" path="pathplanner" revision="refs/heads/main" remote="github"/>
  <!-- ./texts -->
  <project name="krishauser/RoboticSystemsBook" path="text/RoboticSystemsBook" revision="refs/heads/master" remote="github"/>
  <project name="krishauser/Klampt" path="text/Klampt" revision="refs/heads/master" remote="github"/>
  <project name="krishauser/Klampt-jupyter-extension" path="text/Klampt-jupyter-extension" revision="refs/heads/master" remote="github"/>
  <!-- ./dash -->
  <project name="binex-dsk/QFRCDashboard" path="dash/QFRCDashboard" revision="refs/heads/master" remote="github"/>
  <project name="Gold872/elastic-dashboard" path="dash/elastic-dashboard" revision="refs/heads/main" remote="github"/>
  <project name="frc-web-components/frc-web-components" path="dash/frc-web-components" revision="refs/heads/master" remote="github"/>
  <!-- ./dash/shuffleboard -->
  <project name="Mechanical-Advantage/NetworkAlerts" path="dash/shuffleboard/NetworkAlerts" revision="refs/heads/main" />
  <!-- ./dash/advantage -->
  <project name="Mechanical-Advantage/AdvantageKit" path="dash/advantage/AdvantageKit" revision="refs/heads/main" />
  <project name="Mechanical-Advantage/AdvantageScope" path="dash/advantage/AdvantageScope" revision="refs/heads/main" />
  <project name="Mechanical-Advantage/AdvantageScout" path="dash/advantage/AdvantageScout" revision="refs/heads/main" />
  <project name="Mechanical-Advantage/XRPTrainingCode" path="dash/advantage/XRPTrainingCode" revision="refs/heads/main" />
  <!-- ./ide -->
  <project name="javaru/frc-intellij-plugin" path="ide/intellij-2025" revision="refs/heads/main" remote="gitlab" />
  <!-- ./utils -->
  <project name="Boomaa23/open-ds" path="utils/open-ds" revision="refs/heads/master" />
  <project name="StuyPulse/StuyLib" path="utils/stuylib" revision="refs/heads/main" />
  <project name="tervay/recalc" path="utils/recalc" revision="refs/heads/main" />
  <project name="jonahsnider/frc.sh" path="utils/frc.sh" revision="refs/heads/main" />
  <project name="shueja/apriltag-svgs" path="utils/apriltag-svgs" revision="refs/heads/main" />
  <!-- ./AprilRobotics -->
  <project name="AprilRobotics/apriltag" path="AprilRobotics/apriltag" revision="refs/heads/master" />
  <project name="AprilRobotics/apriltag-imgs" path="AprilRobotics/apriltag-imgs" revision="refs/heads/master" />
</manifest>
#+end_src

** Teams

#+begin_src xml :tangle teams.xml :noweb yes
<manifest>
  <project name="Mechanical-Advantage/RobotCode2025Public" path="teams/6328-mechadv/RobotCode2025Public" revision="refs/heads/main" />
  <project name="Mechanical-Advantage/RobotCode2026Public" path="teams/6328-mechadv/RobotCode2026Public" revision="refs/heads/main" />
  <project name="frc2052/2025-Reefscape" path="teams/2052-knightkrawler/2025-Reefscape" revision="refs/heads/main"/>
  <project name="BlueCheese1086/FRC-1086-Offseason-2025-Stringray" path="teams/1086-bluecheese/FRC-1086-Offseason-2025-Stringray" revision="refs/heads/Rewrite"/>
  <project name="Team254/FRC-2025-public" path="teams/254-cheesy-poofs/FRC-2025-public" revision="refs/heads/main"/>
  <project name="Team254/FRC-2024-public" path="teams/254-cheesy-poofs/FRC-2024-public" revision="refs/heads/main"/>
  <project name="Team254/FRC-2023-public" path="teams/254-cheesy-poofs/FRC-2023-public" revision="refs/heads/main"/>
  <project name="Team254/FRC-2022-public" path="teams/254-cheesy-poofs/FRC-2022-public" revision="refs/heads/main"/>
  <project name="Team254/FRC-2020-public" path="teams/254-cheesy-poofs/FRC-2020-public" revision="refs/heads/master"/>
  <project name="Team254/FRC-2019-public" path="teams/254-cheesy-poofs/FRC-2019-public" revision="refs/heads/master"/>
  <project name="Team254/FRC-2018-public" path="teams/254-cheesy-poofs/FRC-2018-public" revision="refs/heads/master"/>
  <project name="Team254/FRC-2017-public" path="teams/254-cheesy-poofs/FRC-2017-public" revision="refs/heads/master"/>
  <project name="Team254/FRC-2016-public" path="teams/254-cheesy-poofs/FRC-2016-public" revision="refs/heads/master"/>
  <project name="FRCTeam2910/2025CompetitionRobot-Public" path="teams/2910-jack-in-the-bot/2025CompetitionRobot-Public" revision="refs/heads/main"/>
  <project name="frc6941/2025-competition-robot" path="teams/6941-iron-pulse/2025-competition-robot" revision="refs/heads/main"/>
  <project name="team401/2026-Robot-Code" path="teams/401-copperhead/2026-Robot-Code" revision="refs/heads/main"/>
  <project name="team401/2025-Robot-Code" path="teams/401-copperhead/2025-Robot-Code" revision="refs/heads/main"/>
  <project name="team401/coppercore" path="teams/401-copperhead/coppercore" revision="refs/heads/main"/>
  <project name="hammerheads5000/2025Reefscape" path="teams/5000-hammerheads/2025Reefscape" revision="refs/heads/main"/>
  <project name="hammerheads5000/2026Rebuilt" path="teams/5000-hammerheads/2026Rebuilt" revision="refs/heads/main"/>
</manifest>
#+end_src

** Cross The Road Electronics

#+begin_src xml :tangle ctre.xml :noweb yes
<manifest>
  <project name="CrossTheRoadElec/Device-CADs" path="ctre/Device-CADs" revision="refs/heads/master" />
  <project name="CrossTheRoadElec/Phoenix6-Documentation" path="ctre/Phoenix6-Documentation" revision="refs/heads/main" />
  <project name="CrossTheRoadElec/Phoenix6-Examples" path="ctre/Phoenix6-Examples" revision="refs/heads/main" />
  <project name="CrossTheRoadElec/Phoenix5-Documentation" path="ctre/Phoenix5-Documentation" revision="refs/heads/dev" />
  <project name="CrossTheRoadElec/Phoenix5-Examples" path="ctre/Phoenix5-Examples" revision="refs/heads/master" />
</manifest>
#+end_src

** Lumyn Labs

https://github.com/Lumyn-Labs/Examples/tree/main/LumynLabsExampleJava

#+begin_src xml :tangle lumyn.xml :noweb yes
<manifest>
  <project name="Lumyn-Labs/Examples" path="lumyn/examples" revision="refs/heads/main" />
  <project name="Lumyn-Labs/docs" path="lumyn/examples" revision="refs/heads/main" />
</manifest>
#+end_src

** Hardware

#+begin_src xml :tangle hardware.xml :noweb yes
<manifest>
  <project name="Team997Coders/TCS34725I2CRoboRio" path="hw/drivers/TCS34725I2CRoboRio" revision="refs/heads/master" />
  <project name="patfair/frc-radio-api" path="hw/vh/frc-radio-api" revision="refs/heads/main" />
  <project name="cinderblock/frc-radio-api" path="hw/vh/frc-radio-api2" revision="refs/heads/main" />
  <project name="wildstang/vh-113_scripts" path="hw/vh/vh-113_scripts" revision="refs/heads/main" />
</manifest>
#+end_src

* Wpilibsuite

Get about 60 of the =wpilibsuite= repositories. These should go into
=/data/ecto/frc/wpilibsuite=.

#+name: wpilibsuiteLogin
#+begin_src emacs-lisp
"wpilibsuite"
#+end_src

Excluded Repositories

#+NAME: wpilibsuiteReposExclude
| .github |

#+name: wpilibsuiteReposFetch
#+call: ghubReposFetch(login=wpilibsuiteLogin)

Clone bundle sizes

#+name: wpilibsuiteReposBundles
#+call: ghubReposBundles(repos=wpilibsuiteReposFetch)

Clone bundles total

#+name: wpilibsuiteReposBundlesTotal
#+call: ghubReposBundlesTotal(tbl=wpilibsuiteReposBundles[,0])

** Wpilibsuite Repos

Filter the results, generate XML

#+name: wpilibsuiteReposXML
#+call: ghubReposXML(repos=wpilibsuiteReposFetch, reposExclude=wpilibsuiteReposExclude, login=wpilibsuiteLogin)

** Generate XML

Generate =wpilibsuite.xml=

#+begin_src xml :tangle wpilibsuite.xml :noweb yes
<manifest>
  <<wpilibsuiteReposXML()>>
</manifest>
#+end_src

* Robotpy

Get about 60 of the =robotpy= repositories. These should go into
=/data/ecto/frc/robotpy=.

#+name: robotpyLogin
#+begin_src emacs-lisp
"robotpy"
#+end_src

Excluded Repositories

#+NAME: robotpyReposExclude
| .github |

#+name: robotpyReposFetch
#+call: ghubReposFetch(login=robotpyLogin)

Clone bundle sizes

#+name: robotpyReposBundles
#+call: ghubReposBundles(repos=robotpyReposFetch)

Clone bundles total

#+name: robotpyReposBundlesTotal
#+call: ghubReposBundlesTotal(tbl=robotpyReposBundles[,0])

** Robotpy Repos

Filter the results, generate XML

#+name: robotpyReposXML
#+call: ghubReposXML(repos=robotpyReposFetch, reposExclude=robotpyReposExclude, login=robotpyLogin)

** Generate XML

Generate =robotpy.xml=

#+begin_src xml :tangle robotpy.xml :noweb yes
<manifest>
  <<robotpyReposXML()>>
</manifest>
#+end_src

* Bb-Frc-Workshops

Get about 60 of the =bb-frc-workshops= repositories. These should go into
=/data/ecto/frc/bb-frc-workshops=.

#+name: bbFrcWorkshopsLogin
#+begin_src emacs-lisp
"bb-frc-workshops"
#+end_src

Excluded Repositories

#+NAME: bbFrcWorkshopsReposExclude
| allwpilib |

#+name: bbFrcWorkshopsReposFetch
#+call: ghubReposFetch(login=bbFrcWorkshopsLogin)

Clone bundle sizes

#+name: bbFrcWorkshopsReposBundles
#+call: ghubReposBundles(repos=bbFrcWorkshopsReposFetch)

Clone bundles total

#+name: bbFrcWorkshopsReposBundlesTotal
#+call: ghubReposBundlesTotal(tbl=bbFrcWorkshopsReposBundles[,0])

** BbFrcWorkshops Repos

Filter the results, generate XML

#+name: bbFrcWorkshopsReposXML
#+call: ghubReposXML(repos=bbFrcWorkshopsReposFetch, reposExclude=bbFrcWorkshopsReposExclude, login="bbFrc")

** Generate XML

Generate =bbFrcWorkshops.xml=

#+begin_src xml :tangle bbFrcWorkshops.xml :noweb yes
<manifest>
  <<bbFrcWorkshopsReposXML()>>
</manifest>
#+end_src

* Photonvision

Get about 60 of the =photonvision= repositories. These should go into
=/data/ecto/frc/photonvision=.

#+name: photonvisionLogin
#+begin_src emacs-lisp
"photonvision"
#+end_src

Excluded Repositories

#+NAME: photonvisionReposExclude
| vendor-json-repo      |
| PhotonPro             |
| champs_2024           |
| opi-image-generator   |
| vue-native-websocket  |
| photonvision-branding |
| photonlib-examples    |
| vue-native-websocket  |

#+name: photonvisionReposFetch
#+call: ghubReposFetch(login=photonvisionLogin)

Clone bundle sizes

#+name: photonvisionReposBundles
#+call: ghubReposBundles(repos=photonvisionReposFetch)

Clone bundles total

#+name: photonvisionReposBundlesTotal
#+call: ghubReposBundlesTotal(tbl=photonvisionReposBundles[,0])

** Photonvision Repos

Filter the results, generate XML

#+name: photonvisionReposXML
#+call: ghubReposXML(repos=photonvisionReposFetch, reposExclude=photonvisionReposExclude, login=photonvisionLogin)

** Generate XML

Generate =photonvision.xml=

#+begin_src xml :tangle photonvision.xml :noweb yes
<manifest>
  <<photonvisionReposXML()>>
</manifest>
#+end_src
